/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryCuttingBySizeResponse implements Serializable {


    @ColumnAlias("pOutCutbySize")
    private List<ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize> poutCutbySize;

    @ColumnAlias("pOutQtyord")
    private List<ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord> poutQtyord;

    public List<ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize> getPoutCutbySize() {
        return this.poutCutbySize;
    }

    public void setPoutCutbySize(List<ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize> poutCutbySize) {
        this.poutCutbySize = poutCutbySize;
    }

    public List<ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord> getPoutQtyord() {
        return this.poutQtyord;
    }

    public void setPoutQtyord(List<ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord> poutQtyord) {
        this.poutQtyord = poutQtyord;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryCuttingBySizeResponse)) return false;
        final ProcCu1000pk0QryCuttingBySizeResponse procCu1000pk0qryCuttingBySizeResponse = (ProcCu1000pk0QryCuttingBySizeResponse) o;
        return Objects.equals(getPoutCutbySize(), procCu1000pk0qryCuttingBySizeResponse.getPoutCutbySize()) &&
                Objects.equals(getPoutQtyord(), procCu1000pk0qryCuttingBySizeResponse.getPoutQtyord());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCutbySize(),
                getPoutQtyord());
    }
}