/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0LastJobRemarksResponsePoutJobRemarks implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("W_CLRDES")
    private String wclrdes;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("W_GMTDES")
    private String wgmtdes;

    @ColumnAlias("W_CLICOD")
    private String wclicod;

    @ColumnAlias("W_SSHPDAT")
    private LocalDateTime wsshpdat;

    @ColumnAlias("W_PCKUNT")
    private BigInteger wpckunt;

    @ColumnAlias("W_PRTPAN")
    private String wprtpan;

    @ColumnAlias("W_PANNUM")
    private String wpannum;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getWclrdes() {
        return this.wclrdes;
    }

    public void setWclrdes(String wclrdes) {
        this.wclrdes = wclrdes;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public String getWgmtdes() {
        return this.wgmtdes;
    }

    public void setWgmtdes(String wgmtdes) {
        this.wgmtdes = wgmtdes;
    }

    public String getWclicod() {
        return this.wclicod;
    }

    public void setWclicod(String wclicod) {
        this.wclicod = wclicod;
    }

    public LocalDateTime getWsshpdat() {
        return this.wsshpdat;
    }

    public void setWsshpdat(LocalDateTime wsshpdat) {
        this.wsshpdat = wsshpdat;
    }

    public BigInteger getWpckunt() {
        return this.wpckunt;
    }

    public void setWpckunt(BigInteger wpckunt) {
        this.wpckunt = wpckunt;
    }

    public String getWprtpan() {
        return this.wprtpan;
    }

    public void setWprtpan(String wprtpan) {
        this.wprtpan = wprtpan;
    }

    public String getWpannum() {
        return this.wpannum;
    }

    public void setWpannum(String wpannum) {
        this.wpannum = wpannum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0LastJobRemarksResponsePoutJobRemarks)) return false;
        final ProcCu1000pk0LastJobRemarksResponsePoutJobRemarks procCu1000pk0lastJobRemarksResponsePoutJobRemarks = (ProcCu1000pk0LastJobRemarksResponsePoutJobRemarks) o;
        return Objects.equals(getOrdnum(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getOrdnum()) &&
                Objects.equals(getClrseq(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getClrseq()) &&
                Objects.equals(getWclrdes(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWclrdes()) &&
                Objects.equals(getGmtseq(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getGmtseq()) &&
                Objects.equals(getWgmtdes(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWgmtdes()) &&
                Objects.equals(getWclicod(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWclicod()) &&
                Objects.equals(getWsshpdat(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWsshpdat()) &&
                Objects.equals(getWpckunt(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWpckunt()) &&
                Objects.equals(getWprtpan(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWprtpan()) &&
                Objects.equals(getWpannum(), procCu1000pk0lastJobRemarksResponsePoutJobRemarks.getWpannum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getClrseq(),
                getWclrdes(),
                getGmtseq(),
                getWgmtdes(),
                getWclicod(),
                getWsshpdat(),
                getWpckunt(),
                getWprtpan(),
                getWpannum());
    }
}