/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu100pk0GetLastRemDetResponse implements Serializable {


    @ColumnAlias("pOutDetailBlock")
    private List<ProcCu100pk0GetLastRemDetResponsePoutDetailBlock> poutDetailBlock;

    public List<ProcCu100pk0GetLastRemDetResponsePoutDetailBlock> getPoutDetailBlock() {
        return this.poutDetailBlock;
    }

    public void setPoutDetailBlock(List<ProcCu100pk0GetLastRemDetResponsePoutDetailBlock> poutDetailBlock) {
        this.poutDetailBlock = poutDetailBlock;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu100pk0GetLastRemDetResponse)) return false;
        final ProcCu100pk0GetLastRemDetResponse procCu100pk0getLastRemDetResponse = (ProcCu100pk0GetLastRemDetResponse) o;
        return Objects.equals(getPoutDetailBlock(), procCu100pk0getLastRemDetResponse.getPoutDetailBlock());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDetailBlock());
    }
}