/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0GetCu900availMarkersResponsePoutMarker implements Serializable {


    @ColumnAlias("SEQ")
    private Short seq;

    @ColumnAlias("VARIANTTYPE")
    private String varianttype;

    @ColumnAlias("STAGE")
    private String stage;

    @ColumnAlias("FABWID")
    private Float fabwid;

    @ColumnAlias("NOPCS")
    private Double nopcs;

    @ColumnAlias("MODELVARIANT")
    private String modelvariant;

    @ColumnAlias("MODEL_FABTYP")
    private String modelFabtyp;

    @ColumnAlias("PATTFILENAME")
    private String pattfilename;

    @ColumnAlias("MARKERFILENAME")
    private String markerfilename;

    @ColumnAlias("MARKERLENGTH")
    private Double markerlength;

    @ColumnAlias("MARKEREFFICIENCY")
    private Float markerefficiency;

    @ColumnAlias("AUTOMARKING_PROCMINUTES")
    private Short automarkingProcminutes;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("SZEDES1")
    private String szedes1;

    @ColumnAlias("SZEDES2")
    private String szedes2;

    @ColumnAlias("SZEDES3")
    private String szedes3;

    @ColumnAlias("SZEDES4")
    private String szedes4;

    @ColumnAlias("SZEDES5")
    private String szedes5;

    @ColumnAlias("SZEDES6")
    private String szedes6;

    @ColumnAlias("SZEDES7")
    private String szedes7;

    @ColumnAlias("SZEDES8")
    private String szedes8;

    @ColumnAlias("SZEDES9")
    private String szedes9;

    @ColumnAlias("SZEDES10")
    private String szedes10;

    @ColumnAlias("SZEDES11")
    private String szedes11;

    @ColumnAlias("SZEDES12")
    private String szedes12;

    @ColumnAlias("SZEDES13")
    private String szedes13;

    @ColumnAlias("SZEDES14")
    private String szedes14;

    @ColumnAlias("SZEDES15")
    private String szedes15;

    @ColumnAlias("SZEDES16")
    private String szedes16;

    @ColumnAlias("LECTCOD1")
    private String lectcod1;

    @ColumnAlias("LECTCOD2")
    private String lectcod2;

    @ColumnAlias("LECTCOD3")
    private String lectcod3;

    @ColumnAlias("LECTCOD4")
    private String lectcod4;

    @ColumnAlias("LECTCOD5")
    private String lectcod5;

    @ColumnAlias("LECTCOD6")
    private String lectcod6;

    @ColumnAlias("LECTCOD7")
    private String lectcod7;

    @ColumnAlias("LECTCOD8")
    private String lectcod8;

    @ColumnAlias("LECTCOD9")
    private String lectcod9;

    @ColumnAlias("LECTCOD10")
    private String lectcod10;

    @ColumnAlias("LECTCOD11")
    private String lectcod11;

    @ColumnAlias("LECTCOD12")
    private String lectcod12;

    @ColumnAlias("LECTCOD13")
    private String lectcod13;

    @ColumnAlias("LECTCOD14")
    private String lectcod14;

    @ColumnAlias("LECTCOD15")
    private String lectcod15;

    @ColumnAlias("LECTCOD16")
    private String lectcod16;

    @ColumnAlias("SZERATIO1")
    private Short szeratio1;

    @ColumnAlias("SZERATIO2")
    private Short szeratio2;

    @ColumnAlias("SZERATIO3")
    private Short szeratio3;

    @ColumnAlias("SZERATIO4")
    private Short szeratio4;

    @ColumnAlias("SZERATIO5")
    private Short szeratio5;

    @ColumnAlias("SZERATIO6")
    private Short szeratio6;

    @ColumnAlias("SZERATIO7")
    private Short szeratio7;

    @ColumnAlias("SZERATIO8")
    private Short szeratio8;

    @ColumnAlias("SZERATIO9")
    private Short szeratio9;

    @ColumnAlias("SZERATIO10")
    private Short szeratio10;

    @ColumnAlias("SZERATIO11")
    private Short szeratio11;

    @ColumnAlias("SZERATIO12")
    private Short szeratio12;

    @ColumnAlias("SZERATIO13")
    private Short szeratio13;

    @ColumnAlias("SZERATIO14")
    private Short szeratio14;

    @ColumnAlias("SZERATIO15")
    private Short szeratio15;

    @ColumnAlias("SZERATIO16")
    private Short szeratio16;

    @ColumnAlias("REVERSEDIR1")
    private String reversedir1;

    @ColumnAlias("REVERSEDIR2")
    private String reversedir2;

    @ColumnAlias("REVERSEDIR3")
    private String reversedir3;

    @ColumnAlias("REVERSEDIR4")
    private String reversedir4;

    @ColumnAlias("REVERSEDIR5")
    private String reversedir5;

    @ColumnAlias("REVERSEDIR6")
    private String reversedir6;

    @ColumnAlias("REVERSEDIR7")
    private String reversedir7;

    @ColumnAlias("REVERSEDIR8")
    private String reversedir8;

    @ColumnAlias("REVERSEDIR9")
    private String reversedir9;

    @ColumnAlias("REVERSEDIR10")
    private String reversedir10;

    @ColumnAlias("REVERSEDIR11")
    private String reversedir11;

    @ColumnAlias("REVERSEDIR12")
    private String reversedir12;

    @ColumnAlias("REVERSEDIR13")
    private String reversedir13;

    @ColumnAlias("REVERSEDIR14")
    private String reversedir14;

    @ColumnAlias("REVERSEDIR15")
    private String reversedir15;

    @ColumnAlias("REVERSEDIR16")
    private String reversedir16;

    @ColumnAlias("GROUPNUM1")
    private Byte groupnum1;

    @ColumnAlias("GROUPNUM2")
    private Byte groupnum2;

    @ColumnAlias("GROUPNUM3")
    private Byte groupnum3;

    @ColumnAlias("GROUPNUM4")
    private Byte groupnum4;

    @ColumnAlias("GROUPNUM5")
    private Byte groupnum5;

    @ColumnAlias("GROUPNUM6")
    private Byte groupnum6;

    @ColumnAlias("GROUPNUM7")
    private Byte groupnum7;

    @ColumnAlias("GROUPNUM8")
    private Byte groupnum8;

    @ColumnAlias("GROUPNUM9")
    private Byte groupnum9;

    @ColumnAlias("GROUPNUM10")
    private Byte groupnum10;

    @ColumnAlias("GROUPNUM11")
    private Byte groupnum11;

    @ColumnAlias("GROUPNUM12")
    private Byte groupnum12;

    @ColumnAlias("GROUPNUM13")
    private Byte groupnum13;

    @ColumnAlias("GROUPNUM14")
    private Byte groupnum14;

    @ColumnAlias("GROUPNUM15")
    private Byte groupnum15;

    @ColumnAlias("GROUPNUM16")
    private Byte groupnum16;

    public Short getSeq() {
        return this.seq;
    }

    public void setSeq(Short seq) {
        this.seq = seq;
    }

    public String getVarianttype() {
        return this.varianttype;
    }

    public void setVarianttype(String varianttype) {
        this.varianttype = varianttype;
    }

    public String getStage() {
        return this.stage;
    }

    public void setStage(String stage) {
        this.stage = stage;
    }

    public Float getFabwid() {
        return this.fabwid;
    }

    public void setFabwid(Float fabwid) {
        this.fabwid = fabwid;
    }

    public Double getNopcs() {
        return this.nopcs;
    }

    public void setNopcs(Double nopcs) {
        this.nopcs = nopcs;
    }

    public String getModelvariant() {
        return this.modelvariant;
    }

    public void setModelvariant(String modelvariant) {
        this.modelvariant = modelvariant;
    }

    public String getModelFabtyp() {
        return this.modelFabtyp;
    }

    public void setModelFabtyp(String modelFabtyp) {
        this.modelFabtyp = modelFabtyp;
    }

    public String getPattfilename() {
        return this.pattfilename;
    }

    public void setPattfilename(String pattfilename) {
        this.pattfilename = pattfilename;
    }

    public String getMarkerfilename() {
        return this.markerfilename;
    }

    public void setMarkerfilename(String markerfilename) {
        this.markerfilename = markerfilename;
    }

    public Double getMarkerlength() {
        return this.markerlength;
    }

    public void setMarkerlength(Double markerlength) {
        this.markerlength = markerlength;
    }

    public Float getMarkerefficiency() {
        return this.markerefficiency;
    }

    public void setMarkerefficiency(Float markerefficiency) {
        this.markerefficiency = markerefficiency;
    }

    public Short getAutomarkingProcminutes() {
        return this.automarkingProcminutes;
    }

    public void setAutomarkingProcminutes(Short automarkingProcminutes) {
        this.automarkingProcminutes = automarkingProcminutes;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public String getSzedes1() {
        return this.szedes1;
    }

    public void setSzedes1(String szedes1) {
        this.szedes1 = szedes1;
    }

    public String getSzedes2() {
        return this.szedes2;
    }

    public void setSzedes2(String szedes2) {
        this.szedes2 = szedes2;
    }

    public String getSzedes3() {
        return this.szedes3;
    }

    public void setSzedes3(String szedes3) {
        this.szedes3 = szedes3;
    }

    public String getSzedes4() {
        return this.szedes4;
    }

    public void setSzedes4(String szedes4) {
        this.szedes4 = szedes4;
    }

    public String getSzedes5() {
        return this.szedes5;
    }

    public void setSzedes5(String szedes5) {
        this.szedes5 = szedes5;
    }

    public String getSzedes6() {
        return this.szedes6;
    }

    public void setSzedes6(String szedes6) {
        this.szedes6 = szedes6;
    }

    public String getSzedes7() {
        return this.szedes7;
    }

    public void setSzedes7(String szedes7) {
        this.szedes7 = szedes7;
    }

    public String getSzedes8() {
        return this.szedes8;
    }

    public void setSzedes8(String szedes8) {
        this.szedes8 = szedes8;
    }

    public String getSzedes9() {
        return this.szedes9;
    }

    public void setSzedes9(String szedes9) {
        this.szedes9 = szedes9;
    }

    public String getSzedes10() {
        return this.szedes10;
    }

    public void setSzedes10(String szedes10) {
        this.szedes10 = szedes10;
    }

    public String getSzedes11() {
        return this.szedes11;
    }

    public void setSzedes11(String szedes11) {
        this.szedes11 = szedes11;
    }

    public String getSzedes12() {
        return this.szedes12;
    }

    public void setSzedes12(String szedes12) {
        this.szedes12 = szedes12;
    }

    public String getSzedes13() {
        return this.szedes13;
    }

    public void setSzedes13(String szedes13) {
        this.szedes13 = szedes13;
    }

    public String getSzedes14() {
        return this.szedes14;
    }

    public void setSzedes14(String szedes14) {
        this.szedes14 = szedes14;
    }

    public String getSzedes15() {
        return this.szedes15;
    }

    public void setSzedes15(String szedes15) {
        this.szedes15 = szedes15;
    }

    public String getSzedes16() {
        return this.szedes16;
    }

    public void setSzedes16(String szedes16) {
        this.szedes16 = szedes16;
    }

    public String getLectcod1() {
        return this.lectcod1;
    }

    public void setLectcod1(String lectcod1) {
        this.lectcod1 = lectcod1;
    }

    public String getLectcod2() {
        return this.lectcod2;
    }

    public void setLectcod2(String lectcod2) {
        this.lectcod2 = lectcod2;
    }

    public String getLectcod3() {
        return this.lectcod3;
    }

    public void setLectcod3(String lectcod3) {
        this.lectcod3 = lectcod3;
    }

    public String getLectcod4() {
        return this.lectcod4;
    }

    public void setLectcod4(String lectcod4) {
        this.lectcod4 = lectcod4;
    }

    public String getLectcod5() {
        return this.lectcod5;
    }

    public void setLectcod5(String lectcod5) {
        this.lectcod5 = lectcod5;
    }

    public String getLectcod6() {
        return this.lectcod6;
    }

    public void setLectcod6(String lectcod6) {
        this.lectcod6 = lectcod6;
    }

    public String getLectcod7() {
        return this.lectcod7;
    }

    public void setLectcod7(String lectcod7) {
        this.lectcod7 = lectcod7;
    }

    public String getLectcod8() {
        return this.lectcod8;
    }

    public void setLectcod8(String lectcod8) {
        this.lectcod8 = lectcod8;
    }

    public String getLectcod9() {
        return this.lectcod9;
    }

    public void setLectcod9(String lectcod9) {
        this.lectcod9 = lectcod9;
    }

    public String getLectcod10() {
        return this.lectcod10;
    }

    public void setLectcod10(String lectcod10) {
        this.lectcod10 = lectcod10;
    }

    public String getLectcod11() {
        return this.lectcod11;
    }

    public void setLectcod11(String lectcod11) {
        this.lectcod11 = lectcod11;
    }

    public String getLectcod12() {
        return this.lectcod12;
    }

    public void setLectcod12(String lectcod12) {
        this.lectcod12 = lectcod12;
    }

    public String getLectcod13() {
        return this.lectcod13;
    }

    public void setLectcod13(String lectcod13) {
        this.lectcod13 = lectcod13;
    }

    public String getLectcod14() {
        return this.lectcod14;
    }

    public void setLectcod14(String lectcod14) {
        this.lectcod14 = lectcod14;
    }

    public String getLectcod15() {
        return this.lectcod15;
    }

    public void setLectcod15(String lectcod15) {
        this.lectcod15 = lectcod15;
    }

    public String getLectcod16() {
        return this.lectcod16;
    }

    public void setLectcod16(String lectcod16) {
        this.lectcod16 = lectcod16;
    }

    public Short getSzeratio1() {
        return this.szeratio1;
    }

    public void setSzeratio1(Short szeratio1) {
        this.szeratio1 = szeratio1;
    }

    public Short getSzeratio2() {
        return this.szeratio2;
    }

    public void setSzeratio2(Short szeratio2) {
        this.szeratio2 = szeratio2;
    }

    public Short getSzeratio3() {
        return this.szeratio3;
    }

    public void setSzeratio3(Short szeratio3) {
        this.szeratio3 = szeratio3;
    }

    public Short getSzeratio4() {
        return this.szeratio4;
    }

    public void setSzeratio4(Short szeratio4) {
        this.szeratio4 = szeratio4;
    }

    public Short getSzeratio5() {
        return this.szeratio5;
    }

    public void setSzeratio5(Short szeratio5) {
        this.szeratio5 = szeratio5;
    }

    public Short getSzeratio6() {
        return this.szeratio6;
    }

    public void setSzeratio6(Short szeratio6) {
        this.szeratio6 = szeratio6;
    }

    public Short getSzeratio7() {
        return this.szeratio7;
    }

    public void setSzeratio7(Short szeratio7) {
        this.szeratio7 = szeratio7;
    }

    public Short getSzeratio8() {
        return this.szeratio8;
    }

    public void setSzeratio8(Short szeratio8) {
        this.szeratio8 = szeratio8;
    }

    public Short getSzeratio9() {
        return this.szeratio9;
    }

    public void setSzeratio9(Short szeratio9) {
        this.szeratio9 = szeratio9;
    }

    public Short getSzeratio10() {
        return this.szeratio10;
    }

    public void setSzeratio10(Short szeratio10) {
        this.szeratio10 = szeratio10;
    }

    public Short getSzeratio11() {
        return this.szeratio11;
    }

    public void setSzeratio11(Short szeratio11) {
        this.szeratio11 = szeratio11;
    }

    public Short getSzeratio12() {
        return this.szeratio12;
    }

    public void setSzeratio12(Short szeratio12) {
        this.szeratio12 = szeratio12;
    }

    public Short getSzeratio13() {
        return this.szeratio13;
    }

    public void setSzeratio13(Short szeratio13) {
        this.szeratio13 = szeratio13;
    }

    public Short getSzeratio14() {
        return this.szeratio14;
    }

    public void setSzeratio14(Short szeratio14) {
        this.szeratio14 = szeratio14;
    }

    public Short getSzeratio15() {
        return this.szeratio15;
    }

    public void setSzeratio15(Short szeratio15) {
        this.szeratio15 = szeratio15;
    }

    public Short getSzeratio16() {
        return this.szeratio16;
    }

    public void setSzeratio16(Short szeratio16) {
        this.szeratio16 = szeratio16;
    }

    public String getReversedir1() {
        return this.reversedir1;
    }

    public void setReversedir1(String reversedir1) {
        this.reversedir1 = reversedir1;
    }

    public String getReversedir2() {
        return this.reversedir2;
    }

    public void setReversedir2(String reversedir2) {
        this.reversedir2 = reversedir2;
    }

    public String getReversedir3() {
        return this.reversedir3;
    }

    public void setReversedir3(String reversedir3) {
        this.reversedir3 = reversedir3;
    }

    public String getReversedir4() {
        return this.reversedir4;
    }

    public void setReversedir4(String reversedir4) {
        this.reversedir4 = reversedir4;
    }

    public String getReversedir5() {
        return this.reversedir5;
    }

    public void setReversedir5(String reversedir5) {
        this.reversedir5 = reversedir5;
    }

    public String getReversedir6() {
        return this.reversedir6;
    }

    public void setReversedir6(String reversedir6) {
        this.reversedir6 = reversedir6;
    }

    public String getReversedir7() {
        return this.reversedir7;
    }

    public void setReversedir7(String reversedir7) {
        this.reversedir7 = reversedir7;
    }

    public String getReversedir8() {
        return this.reversedir8;
    }

    public void setReversedir8(String reversedir8) {
        this.reversedir8 = reversedir8;
    }

    public String getReversedir9() {
        return this.reversedir9;
    }

    public void setReversedir9(String reversedir9) {
        this.reversedir9 = reversedir9;
    }

    public String getReversedir10() {
        return this.reversedir10;
    }

    public void setReversedir10(String reversedir10) {
        this.reversedir10 = reversedir10;
    }

    public String getReversedir11() {
        return this.reversedir11;
    }

    public void setReversedir11(String reversedir11) {
        this.reversedir11 = reversedir11;
    }

    public String getReversedir12() {
        return this.reversedir12;
    }

    public void setReversedir12(String reversedir12) {
        this.reversedir12 = reversedir12;
    }

    public String getReversedir13() {
        return this.reversedir13;
    }

    public void setReversedir13(String reversedir13) {
        this.reversedir13 = reversedir13;
    }

    public String getReversedir14() {
        return this.reversedir14;
    }

    public void setReversedir14(String reversedir14) {
        this.reversedir14 = reversedir14;
    }

    public String getReversedir15() {
        return this.reversedir15;
    }

    public void setReversedir15(String reversedir15) {
        this.reversedir15 = reversedir15;
    }

    public String getReversedir16() {
        return this.reversedir16;
    }

    public void setReversedir16(String reversedir16) {
        this.reversedir16 = reversedir16;
    }

    public Byte getGroupnum1() {
        return this.groupnum1;
    }

    public void setGroupnum1(Byte groupnum1) {
        this.groupnum1 = groupnum1;
    }

    public Byte getGroupnum2() {
        return this.groupnum2;
    }

    public void setGroupnum2(Byte groupnum2) {
        this.groupnum2 = groupnum2;
    }

    public Byte getGroupnum3() {
        return this.groupnum3;
    }

    public void setGroupnum3(Byte groupnum3) {
        this.groupnum3 = groupnum3;
    }

    public Byte getGroupnum4() {
        return this.groupnum4;
    }

    public void setGroupnum4(Byte groupnum4) {
        this.groupnum4 = groupnum4;
    }

    public Byte getGroupnum5() {
        return this.groupnum5;
    }

    public void setGroupnum5(Byte groupnum5) {
        this.groupnum5 = groupnum5;
    }

    public Byte getGroupnum6() {
        return this.groupnum6;
    }

    public void setGroupnum6(Byte groupnum6) {
        this.groupnum6 = groupnum6;
    }

    public Byte getGroupnum7() {
        return this.groupnum7;
    }

    public void setGroupnum7(Byte groupnum7) {
        this.groupnum7 = groupnum7;
    }

    public Byte getGroupnum8() {
        return this.groupnum8;
    }

    public void setGroupnum8(Byte groupnum8) {
        this.groupnum8 = groupnum8;
    }

    public Byte getGroupnum9() {
        return this.groupnum9;
    }

    public void setGroupnum9(Byte groupnum9) {
        this.groupnum9 = groupnum9;
    }

    public Byte getGroupnum10() {
        return this.groupnum10;
    }

    public void setGroupnum10(Byte groupnum10) {
        this.groupnum10 = groupnum10;
    }

    public Byte getGroupnum11() {
        return this.groupnum11;
    }

    public void setGroupnum11(Byte groupnum11) {
        this.groupnum11 = groupnum11;
    }

    public Byte getGroupnum12() {
        return this.groupnum12;
    }

    public void setGroupnum12(Byte groupnum12) {
        this.groupnum12 = groupnum12;
    }

    public Byte getGroupnum13() {
        return this.groupnum13;
    }

    public void setGroupnum13(Byte groupnum13) {
        this.groupnum13 = groupnum13;
    }

    public Byte getGroupnum14() {
        return this.groupnum14;
    }

    public void setGroupnum14(Byte groupnum14) {
        this.groupnum14 = groupnum14;
    }

    public Byte getGroupnum15() {
        return this.groupnum15;
    }

    public void setGroupnum15(Byte groupnum15) {
        this.groupnum15 = groupnum15;
    }

    public Byte getGroupnum16() {
        return this.groupnum16;
    }

    public void setGroupnum16(Byte groupnum16) {
        this.groupnum16 = groupnum16;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0GetCu900availMarkersResponsePoutMarker)) return false;
        final ProcCu1000pk0GetCu900availMarkersResponsePoutMarker procCu1000pk0getCu900availMarkersResponsePoutMarker = (ProcCu1000pk0GetCu900availMarkersResponsePoutMarker) o;
        return Objects.equals(getSeq(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSeq()) &&
                Objects.equals(getVarianttype(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getVarianttype()) &&
                Objects.equals(getStage(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getStage()) &&
                Objects.equals(getFabwid(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getFabwid()) &&
                Objects.equals(getNopcs(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getNopcs()) &&
                Objects.equals(getModelvariant(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getModelvariant()) &&
                Objects.equals(getModelFabtyp(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getModelFabtyp()) &&
                Objects.equals(getPattfilename(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getPattfilename()) &&
                Objects.equals(getMarkerfilename(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getMarkerfilename()) &&
                Objects.equals(getMarkerlength(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getMarkerlength()) &&
                Objects.equals(getMarkerefficiency(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getMarkerefficiency()) &&
                Objects.equals(getAutomarkingProcminutes(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getAutomarkingProcminutes()) &&
                Objects.equals(getStatus(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getStatus()) &&
                Objects.equals(getRemarks(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getRemarks()) &&
                Objects.equals(getDyejob(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getDyejob()) &&
                Objects.equals(getSzedes1(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes1()) &&
                Objects.equals(getSzedes2(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes2()) &&
                Objects.equals(getSzedes3(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes3()) &&
                Objects.equals(getSzedes4(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes4()) &&
                Objects.equals(getSzedes5(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes5()) &&
                Objects.equals(getSzedes6(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes6()) &&
                Objects.equals(getSzedes7(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes7()) &&
                Objects.equals(getSzedes8(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes8()) &&
                Objects.equals(getSzedes9(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes9()) &&
                Objects.equals(getSzedes10(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes10()) &&
                Objects.equals(getSzedes11(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes11()) &&
                Objects.equals(getSzedes12(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes12()) &&
                Objects.equals(getSzedes13(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes13()) &&
                Objects.equals(getSzedes14(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes14()) &&
                Objects.equals(getSzedes15(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes15()) &&
                Objects.equals(getSzedes16(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzedes16()) &&
                Objects.equals(getLectcod1(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod1()) &&
                Objects.equals(getLectcod2(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod2()) &&
                Objects.equals(getLectcod3(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod3()) &&
                Objects.equals(getLectcod4(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod4()) &&
                Objects.equals(getLectcod5(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod5()) &&
                Objects.equals(getLectcod6(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod6()) &&
                Objects.equals(getLectcod7(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod7()) &&
                Objects.equals(getLectcod8(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod8()) &&
                Objects.equals(getLectcod9(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod9()) &&
                Objects.equals(getLectcod10(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod10()) &&
                Objects.equals(getLectcod11(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod11()) &&
                Objects.equals(getLectcod12(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod12()) &&
                Objects.equals(getLectcod13(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod13()) &&
                Objects.equals(getLectcod14(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod14()) &&
                Objects.equals(getLectcod15(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod15()) &&
                Objects.equals(getLectcod16(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getLectcod16()) &&
                Objects.equals(getSzeratio1(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio1()) &&
                Objects.equals(getSzeratio2(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio2()) &&
                Objects.equals(getSzeratio3(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio3()) &&
                Objects.equals(getSzeratio4(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio4()) &&
                Objects.equals(getSzeratio5(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio5()) &&
                Objects.equals(getSzeratio6(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio6()) &&
                Objects.equals(getSzeratio7(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio7()) &&
                Objects.equals(getSzeratio8(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio8()) &&
                Objects.equals(getSzeratio9(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio9()) &&
                Objects.equals(getSzeratio10(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio10()) &&
                Objects.equals(getSzeratio11(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio11()) &&
                Objects.equals(getSzeratio12(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio12()) &&
                Objects.equals(getSzeratio13(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio13()) &&
                Objects.equals(getSzeratio14(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio14()) &&
                Objects.equals(getSzeratio15(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio15()) &&
                Objects.equals(getSzeratio16(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getSzeratio16()) &&
                Objects.equals(getReversedir1(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir1()) &&
                Objects.equals(getReversedir2(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir2()) &&
                Objects.equals(getReversedir3(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir3()) &&
                Objects.equals(getReversedir4(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir4()) &&
                Objects.equals(getReversedir5(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir5()) &&
                Objects.equals(getReversedir6(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir6()) &&
                Objects.equals(getReversedir7(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir7()) &&
                Objects.equals(getReversedir8(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir8()) &&
                Objects.equals(getReversedir9(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir9()) &&
                Objects.equals(getReversedir10(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir10()) &&
                Objects.equals(getReversedir11(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir11()) &&
                Objects.equals(getReversedir12(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir12()) &&
                Objects.equals(getReversedir13(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir13()) &&
                Objects.equals(getReversedir14(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir14()) &&
                Objects.equals(getReversedir15(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir15()) &&
                Objects.equals(getReversedir16(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getReversedir16()) &&
                Objects.equals(getGroupnum1(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum1()) &&
                Objects.equals(getGroupnum2(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum2()) &&
                Objects.equals(getGroupnum3(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum3()) &&
                Objects.equals(getGroupnum4(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum4()) &&
                Objects.equals(getGroupnum5(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum5()) &&
                Objects.equals(getGroupnum6(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum6()) &&
                Objects.equals(getGroupnum7(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum7()) &&
                Objects.equals(getGroupnum8(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum8()) &&
                Objects.equals(getGroupnum9(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum9()) &&
                Objects.equals(getGroupnum10(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum10()) &&
                Objects.equals(getGroupnum11(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum11()) &&
                Objects.equals(getGroupnum12(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum12()) &&
                Objects.equals(getGroupnum13(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum13()) &&
                Objects.equals(getGroupnum14(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum14()) &&
                Objects.equals(getGroupnum15(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum15()) &&
                Objects.equals(getGroupnum16(), procCu1000pk0getCu900availMarkersResponsePoutMarker.getGroupnum16());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSeq(),
                getVarianttype(),
                getStage(),
                getFabwid(),
                getNopcs(),
                getModelvariant(),
                getModelFabtyp(),
                getPattfilename(),
                getMarkerfilename(),
                getMarkerlength(),
                getMarkerefficiency(),
                getAutomarkingProcminutes(),
                getStatus(),
                getRemarks(),
                getDyejob(),
                getSzedes1(),
                getSzedes2(),
                getSzedes3(),
                getSzedes4(),
                getSzedes5(),
                getSzedes6(),
                getSzedes7(),
                getSzedes8(),
                getSzedes9(),
                getSzedes10(),
                getSzedes11(),
                getSzedes12(),
                getSzedes13(),
                getSzedes14(),
                getSzedes15(),
                getSzedes16(),
                getLectcod1(),
                getLectcod2(),
                getLectcod3(),
                getLectcod4(),
                getLectcod5(),
                getLectcod6(),
                getLectcod7(),
                getLectcod8(),
                getLectcod9(),
                getLectcod10(),
                getLectcod11(),
                getLectcod12(),
                getLectcod13(),
                getLectcod14(),
                getLectcod15(),
                getLectcod16(),
                getSzeratio1(),
                getSzeratio2(),
                getSzeratio3(),
                getSzeratio4(),
                getSzeratio5(),
                getSzeratio6(),
                getSzeratio7(),
                getSzeratio8(),
                getSzeratio9(),
                getSzeratio10(),
                getSzeratio11(),
                getSzeratio12(),
                getSzeratio13(),
                getSzeratio14(),
                getSzeratio15(),
                getSzeratio16(),
                getReversedir1(),
                getReversedir2(),
                getReversedir3(),
                getReversedir4(),
                getReversedir5(),
                getReversedir6(),
                getReversedir7(),
                getReversedir8(),
                getReversedir9(),
                getReversedir10(),
                getReversedir11(),
                getReversedir12(),
                getReversedir13(),
                getReversedir14(),
                getReversedir15(),
                getReversedir16(),
                getGroupnum1(),
                getGroupnum2(),
                getGroupnum3(),
                getGroupnum4(),
                getGroupnum5(),
                getGroupnum6(),
                getGroupnum7(),
                getGroupnum8(),
                getGroupnum9(),
                getGroupnum10(),
                getGroupnum11(),
                getGroupnum12(),
                getGroupnum13(),
                getGroupnum14(),
                getGroupnum15(),
                getGroupnum16());
    }
}