/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0GetCu900availMarkersResponse implements Serializable {


    @ColumnAlias("pOutMarker")
    private List<ProcCu1000pk0GetCu900availMarkersResponsePoutMarker> poutMarker;

    public List<ProcCu1000pk0GetCu900availMarkersResponsePoutMarker> getPoutMarker() {
        return this.poutMarker;
    }

    public void setPoutMarker(List<ProcCu1000pk0GetCu900availMarkersResponsePoutMarker> poutMarker) {
        this.poutMarker = poutMarker;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0GetCu900availMarkersResponse)) return false;
        final ProcCu1000pk0GetCu900availMarkersResponse procCu1000pk0getCu900availMarkersResponse = (ProcCu1000pk0GetCu900availMarkersResponse) o;
        return Objects.equals(getPoutMarker(), procCu1000pk0getCu900availMarkersResponse.getPoutMarker());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMarker());
    }
}