/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes implements Serializable {


    @ColumnAlias("SZESEQ")
    private Byte szeseq;

    @ColumnAlias("SIZEDES")
    private String sizedes;

    @ColumnAlias("SZEDES")
    private String szedes;

    @ColumnAlias("CLIREF")
    private String cliref;

    @ColumnAlias("LECTCOD")
    private String lectcod;

    public Byte getSzeseq() {
        return this.szeseq;
    }

    public void setSzeseq(Byte szeseq) {
        this.szeseq = szeseq;
    }

    public String getSizedes() {
        return this.sizedes;
    }

    public void setSizedes(String sizedes) {
        this.sizedes = sizedes;
    }

    public String getSzedes() {
        return this.szedes;
    }

    public void setSzedes(String szedes) {
        this.szedes = szedes;
    }

    public String getCliref() {
        return this.cliref;
    }

    public void setCliref(String cliref) {
        this.cliref = cliref;
    }

    public String getLectcod() {
        return this.lectcod;
    }

    public void setLectcod(String lectcod) {
        this.lectcod = lectcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes)) return false;
        final ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes procCu1000pk0qryCutBySizeOrderDetResponsePoutSizes = (ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes) o;
        return Objects.equals(getSzeseq(), procCu1000pk0qryCutBySizeOrderDetResponsePoutSizes.getSzeseq()) &&
                Objects.equals(getSizedes(), procCu1000pk0qryCutBySizeOrderDetResponsePoutSizes.getSizedes()) &&
                Objects.equals(getSzedes(), procCu1000pk0qryCutBySizeOrderDetResponsePoutSizes.getSzedes()) &&
                Objects.equals(getCliref(), procCu1000pk0qryCutBySizeOrderDetResponsePoutSizes.getCliref()) &&
                Objects.equals(getLectcod(), procCu1000pk0qryCutBySizeOrderDetResponsePoutSizes.getLectcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSzeseq(),
                getSizedes(),
                getSzedes(),
                getCliref(),
                getLectcod());
    }
}