/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord implements Serializable {


    @ColumnAlias("QTYORD1")
    private BigInteger qtyord1;

    @ColumnAlias("QTYORD2")
    private BigInteger qtyord2;

    @ColumnAlias("QTYORD3")
    private BigInteger qtyord3;

    @ColumnAlias("QTYORD4")
    private BigInteger qtyord4;

    @ColumnAlias("QTYORD5")
    private BigInteger qtyord5;

    @ColumnAlias("QTYORD6")
    private BigInteger qtyord6;

    @ColumnAlias("QTYORD7")
    private BigInteger qtyord7;

    @ColumnAlias("QTYORD8")
    private BigInteger qtyord8;

    @ColumnAlias("QTYORD9")
    private BigInteger qtyord9;

    @ColumnAlias("QTYORD10")
    private BigInteger qtyord10;

    @ColumnAlias("QTYORD11")
    private BigInteger qtyord11;

    @ColumnAlias("QTYORD12")
    private BigInteger qtyord12;

    @ColumnAlias("QTYORD13")
    private BigInteger qtyord13;

    @ColumnAlias("QTYORD14")
    private BigInteger qtyord14;

    @ColumnAlias("QTYORD15")
    private BigInteger qtyord15;

    @ColumnAlias("QTYORD16")
    private BigInteger qtyord16;

    @ColumnAlias("QTYORD17")
    private BigInteger qtyord17;

    @ColumnAlias("QTYORD18")
    private BigInteger qtyord18;

    @ColumnAlias("QTYORD19")
    private BigInteger qtyord19;

    @ColumnAlias("QTYORD20")
    private BigInteger qtyord20;

    @ColumnAlias("QTYORD21")
    private BigInteger qtyord21;

    @ColumnAlias("QTYORD22")
    private BigInteger qtyord22;

    @ColumnAlias("QTYORD23")
    private BigInteger qtyord23;

    @ColumnAlias("QTYORD24")
    private BigInteger qtyord24;

    @ColumnAlias("QTYORD25")
    private BigInteger qtyord25;

    @ColumnAlias("QTYORD26")
    private BigInteger qtyord26;

    @ColumnAlias("QTYORD27")
    private BigInteger qtyord27;

    @ColumnAlias("QTYORD28")
    private BigInteger qtyord28;

    @ColumnAlias("QTYORD29")
    private BigInteger qtyord29;

    @ColumnAlias("QTYORD30")
    private BigInteger qtyord30;

    @ColumnAlias("QTYORD31")
    private BigInteger qtyord31;

    @ColumnAlias("QTYORD32")
    private BigInteger qtyord32;

    @ColumnAlias("QTYORD33")
    private BigInteger qtyord33;

    @ColumnAlias("QTYORD34")
    private BigInteger qtyord34;

    @ColumnAlias("QTYORD35")
    private BigInteger qtyord35;

    @ColumnAlias("QTYORD36")
    private BigInteger qtyord36;

    @ColumnAlias("QTYORD37")
    private BigInteger qtyord37;

    @ColumnAlias("QTYORD38")
    private BigInteger qtyord38;

    @ColumnAlias("QTYORD39")
    private BigInteger qtyord39;

    @ColumnAlias("QTYORD40")
    private BigInteger qtyord40;

    @ColumnAlias("QTYORD41")
    private BigInteger qtyord41;

    @ColumnAlias("QTYORD42")
    private BigInteger qtyord42;

    @ColumnAlias("QTYORD43")
    private BigInteger qtyord43;

    @ColumnAlias("QTYORD44")
    private BigInteger qtyord44;

    @ColumnAlias("QTYORD45")
    private BigInteger qtyord45;

    @ColumnAlias("QTYORD46")
    private BigInteger qtyord46;

    @ColumnAlias("QTYORD47")
    private BigInteger qtyord47;

    @ColumnAlias("QTYORD48")
    private BigInteger qtyord48;

    @ColumnAlias("TOTPCS")
    private BigInteger totpcs;

    public BigInteger getQtyord1() {
        return this.qtyord1;
    }

    public void setQtyord1(BigInteger qtyord1) {
        this.qtyord1 = qtyord1;
    }

    public BigInteger getQtyord2() {
        return this.qtyord2;
    }

    public void setQtyord2(BigInteger qtyord2) {
        this.qtyord2 = qtyord2;
    }

    public BigInteger getQtyord3() {
        return this.qtyord3;
    }

    public void setQtyord3(BigInteger qtyord3) {
        this.qtyord3 = qtyord3;
    }

    public BigInteger getQtyord4() {
        return this.qtyord4;
    }

    public void setQtyord4(BigInteger qtyord4) {
        this.qtyord4 = qtyord4;
    }

    public BigInteger getQtyord5() {
        return this.qtyord5;
    }

    public void setQtyord5(BigInteger qtyord5) {
        this.qtyord5 = qtyord5;
    }

    public BigInteger getQtyord6() {
        return this.qtyord6;
    }

    public void setQtyord6(BigInteger qtyord6) {
        this.qtyord6 = qtyord6;
    }

    public BigInteger getQtyord7() {
        return this.qtyord7;
    }

    public void setQtyord7(BigInteger qtyord7) {
        this.qtyord7 = qtyord7;
    }

    public BigInteger getQtyord8() {
        return this.qtyord8;
    }

    public void setQtyord8(BigInteger qtyord8) {
        this.qtyord8 = qtyord8;
    }

    public BigInteger getQtyord9() {
        return this.qtyord9;
    }

    public void setQtyord9(BigInteger qtyord9) {
        this.qtyord9 = qtyord9;
    }

    public BigInteger getQtyord10() {
        return this.qtyord10;
    }

    public void setQtyord10(BigInteger qtyord10) {
        this.qtyord10 = qtyord10;
    }

    public BigInteger getQtyord11() {
        return this.qtyord11;
    }

    public void setQtyord11(BigInteger qtyord11) {
        this.qtyord11 = qtyord11;
    }

    public BigInteger getQtyord12() {
        return this.qtyord12;
    }

    public void setQtyord12(BigInteger qtyord12) {
        this.qtyord12 = qtyord12;
    }

    public BigInteger getQtyord13() {
        return this.qtyord13;
    }

    public void setQtyord13(BigInteger qtyord13) {
        this.qtyord13 = qtyord13;
    }

    public BigInteger getQtyord14() {
        return this.qtyord14;
    }

    public void setQtyord14(BigInteger qtyord14) {
        this.qtyord14 = qtyord14;
    }

    public BigInteger getQtyord15() {
        return this.qtyord15;
    }

    public void setQtyord15(BigInteger qtyord15) {
        this.qtyord15 = qtyord15;
    }

    public BigInteger getQtyord16() {
        return this.qtyord16;
    }

    public void setQtyord16(BigInteger qtyord16) {
        this.qtyord16 = qtyord16;
    }

    public BigInteger getQtyord17() {
        return this.qtyord17;
    }

    public void setQtyord17(BigInteger qtyord17) {
        this.qtyord17 = qtyord17;
    }

    public BigInteger getQtyord18() {
        return this.qtyord18;
    }

    public void setQtyord18(BigInteger qtyord18) {
        this.qtyord18 = qtyord18;
    }

    public BigInteger getQtyord19() {
        return this.qtyord19;
    }

    public void setQtyord19(BigInteger qtyord19) {
        this.qtyord19 = qtyord19;
    }

    public BigInteger getQtyord20() {
        return this.qtyord20;
    }

    public void setQtyord20(BigInteger qtyord20) {
        this.qtyord20 = qtyord20;
    }

    public BigInteger getQtyord21() {
        return this.qtyord21;
    }

    public void setQtyord21(BigInteger qtyord21) {
        this.qtyord21 = qtyord21;
    }

    public BigInteger getQtyord22() {
        return this.qtyord22;
    }

    public void setQtyord22(BigInteger qtyord22) {
        this.qtyord22 = qtyord22;
    }

    public BigInteger getQtyord23() {
        return this.qtyord23;
    }

    public void setQtyord23(BigInteger qtyord23) {
        this.qtyord23 = qtyord23;
    }

    public BigInteger getQtyord24() {
        return this.qtyord24;
    }

    public void setQtyord24(BigInteger qtyord24) {
        this.qtyord24 = qtyord24;
    }

    public BigInteger getQtyord25() {
        return this.qtyord25;
    }

    public void setQtyord25(BigInteger qtyord25) {
        this.qtyord25 = qtyord25;
    }

    public BigInteger getQtyord26() {
        return this.qtyord26;
    }

    public void setQtyord26(BigInteger qtyord26) {
        this.qtyord26 = qtyord26;
    }

    public BigInteger getQtyord27() {
        return this.qtyord27;
    }

    public void setQtyord27(BigInteger qtyord27) {
        this.qtyord27 = qtyord27;
    }

    public BigInteger getQtyord28() {
        return this.qtyord28;
    }

    public void setQtyord28(BigInteger qtyord28) {
        this.qtyord28 = qtyord28;
    }

    public BigInteger getQtyord29() {
        return this.qtyord29;
    }

    public void setQtyord29(BigInteger qtyord29) {
        this.qtyord29 = qtyord29;
    }

    public BigInteger getQtyord30() {
        return this.qtyord30;
    }

    public void setQtyord30(BigInteger qtyord30) {
        this.qtyord30 = qtyord30;
    }

    public BigInteger getQtyord31() {
        return this.qtyord31;
    }

    public void setQtyord31(BigInteger qtyord31) {
        this.qtyord31 = qtyord31;
    }

    public BigInteger getQtyord32() {
        return this.qtyord32;
    }

    public void setQtyord32(BigInteger qtyord32) {
        this.qtyord32 = qtyord32;
    }

    public BigInteger getQtyord33() {
        return this.qtyord33;
    }

    public void setQtyord33(BigInteger qtyord33) {
        this.qtyord33 = qtyord33;
    }

    public BigInteger getQtyord34() {
        return this.qtyord34;
    }

    public void setQtyord34(BigInteger qtyord34) {
        this.qtyord34 = qtyord34;
    }

    public BigInteger getQtyord35() {
        return this.qtyord35;
    }

    public void setQtyord35(BigInteger qtyord35) {
        this.qtyord35 = qtyord35;
    }

    public BigInteger getQtyord36() {
        return this.qtyord36;
    }

    public void setQtyord36(BigInteger qtyord36) {
        this.qtyord36 = qtyord36;
    }

    public BigInteger getQtyord37() {
        return this.qtyord37;
    }

    public void setQtyord37(BigInteger qtyord37) {
        this.qtyord37 = qtyord37;
    }

    public BigInteger getQtyord38() {
        return this.qtyord38;
    }

    public void setQtyord38(BigInteger qtyord38) {
        this.qtyord38 = qtyord38;
    }

    public BigInteger getQtyord39() {
        return this.qtyord39;
    }

    public void setQtyord39(BigInteger qtyord39) {
        this.qtyord39 = qtyord39;
    }

    public BigInteger getQtyord40() {
        return this.qtyord40;
    }

    public void setQtyord40(BigInteger qtyord40) {
        this.qtyord40 = qtyord40;
    }

    public BigInteger getQtyord41() {
        return this.qtyord41;
    }

    public void setQtyord41(BigInteger qtyord41) {
        this.qtyord41 = qtyord41;
    }

    public BigInteger getQtyord42() {
        return this.qtyord42;
    }

    public void setQtyord42(BigInteger qtyord42) {
        this.qtyord42 = qtyord42;
    }

    public BigInteger getQtyord43() {
        return this.qtyord43;
    }

    public void setQtyord43(BigInteger qtyord43) {
        this.qtyord43 = qtyord43;
    }

    public BigInteger getQtyord44() {
        return this.qtyord44;
    }

    public void setQtyord44(BigInteger qtyord44) {
        this.qtyord44 = qtyord44;
    }

    public BigInteger getQtyord45() {
        return this.qtyord45;
    }

    public void setQtyord45(BigInteger qtyord45) {
        this.qtyord45 = qtyord45;
    }

    public BigInteger getQtyord46() {
        return this.qtyord46;
    }

    public void setQtyord46(BigInteger qtyord46) {
        this.qtyord46 = qtyord46;
    }

    public BigInteger getQtyord47() {
        return this.qtyord47;
    }

    public void setQtyord47(BigInteger qtyord47) {
        this.qtyord47 = qtyord47;
    }

    public BigInteger getQtyord48() {
        return this.qtyord48;
    }

    public void setQtyord48(BigInteger qtyord48) {
        this.qtyord48 = qtyord48;
    }

    public BigInteger getTotpcs() {
        return this.totpcs;
    }

    public void setTotpcs(BigInteger totpcs) {
        this.totpcs = totpcs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord)) return false;
        final ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord procCu1000pk0qryCuttingBySizeResponsePoutQtyord = (ProcCu1000pk0QryCuttingBySizeResponsePoutQtyord) o;
        return Objects.equals(getQtyord1(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord1()) &&
                Objects.equals(getQtyord2(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord2()) &&
                Objects.equals(getQtyord3(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord3()) &&
                Objects.equals(getQtyord4(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord4()) &&
                Objects.equals(getQtyord5(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord5()) &&
                Objects.equals(getQtyord6(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord6()) &&
                Objects.equals(getQtyord7(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord7()) &&
                Objects.equals(getQtyord8(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord8()) &&
                Objects.equals(getQtyord9(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord9()) &&
                Objects.equals(getQtyord10(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord10()) &&
                Objects.equals(getQtyord11(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord11()) &&
                Objects.equals(getQtyord12(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord12()) &&
                Objects.equals(getQtyord13(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord13()) &&
                Objects.equals(getQtyord14(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord14()) &&
                Objects.equals(getQtyord15(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord15()) &&
                Objects.equals(getQtyord16(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord16()) &&
                Objects.equals(getQtyord17(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord17()) &&
                Objects.equals(getQtyord18(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord18()) &&
                Objects.equals(getQtyord19(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord19()) &&
                Objects.equals(getQtyord20(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord20()) &&
                Objects.equals(getQtyord21(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord21()) &&
                Objects.equals(getQtyord22(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord22()) &&
                Objects.equals(getQtyord23(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord23()) &&
                Objects.equals(getQtyord24(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord24()) &&
                Objects.equals(getQtyord25(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord25()) &&
                Objects.equals(getQtyord26(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord26()) &&
                Objects.equals(getQtyord27(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord27()) &&
                Objects.equals(getQtyord28(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord28()) &&
                Objects.equals(getQtyord29(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord29()) &&
                Objects.equals(getQtyord30(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord30()) &&
                Objects.equals(getQtyord31(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord31()) &&
                Objects.equals(getQtyord32(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord32()) &&
                Objects.equals(getQtyord33(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord33()) &&
                Objects.equals(getQtyord34(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord34()) &&
                Objects.equals(getQtyord35(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord35()) &&
                Objects.equals(getQtyord36(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord36()) &&
                Objects.equals(getQtyord37(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord37()) &&
                Objects.equals(getQtyord38(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord38()) &&
                Objects.equals(getQtyord39(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord39()) &&
                Objects.equals(getQtyord40(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord40()) &&
                Objects.equals(getQtyord41(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord41()) &&
                Objects.equals(getQtyord42(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord42()) &&
                Objects.equals(getQtyord43(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord43()) &&
                Objects.equals(getQtyord44(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord44()) &&
                Objects.equals(getQtyord45(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord45()) &&
                Objects.equals(getQtyord46(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord46()) &&
                Objects.equals(getQtyord47(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord47()) &&
                Objects.equals(getQtyord48(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getQtyord48()) &&
                Objects.equals(getTotpcs(), procCu1000pk0qryCuttingBySizeResponsePoutQtyord.getTotpcs());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getQtyord1(),
                getQtyord2(),
                getQtyord3(),
                getQtyord4(),
                getQtyord5(),
                getQtyord6(),
                getQtyord7(),
                getQtyord8(),
                getQtyord9(),
                getQtyord10(),
                getQtyord11(),
                getQtyord12(),
                getQtyord13(),
                getQtyord14(),
                getQtyord15(),
                getQtyord16(),
                getQtyord17(),
                getQtyord18(),
                getQtyord19(),
                getQtyord20(),
                getQtyord21(),
                getQtyord22(),
                getQtyord23(),
                getQtyord24(),
                getQtyord25(),
                getQtyord26(),
                getQtyord27(),
                getQtyord28(),
                getQtyord29(),
                getQtyord30(),
                getQtyord31(),
                getQtyord32(),
                getQtyord33(),
                getQtyord34(),
                getQtyord35(),
                getQtyord36(),
                getQtyord37(),
                getQtyord38(),
                getQtyord39(),
                getQtyord40(),
                getQtyord41(),
                getQtyord42(),
                getQtyord43(),
                getQtyord44(),
                getQtyord45(),
                getQtyord46(),
                getQtyord47(),
                getQtyord48(),
                getTotpcs());
    }
}