/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize implements Serializable {


    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("FABIND")
    private String fabind;

    @ColumnAlias("FABCLRDES")
    private String fabclrdes;

    @ColumnAlias("CUTSEQ")
    private BigDecimal cutseq;

    @ColumnAlias("CUTDATE")
    private String cutdate;

    @ColumnAlias("KGS")
    private BigDecimal kgs;

    @ColumnAlias("CUTAVG")
    private BigDecimal cutavg;

    @ColumnAlias("KGSCUT")
    private BigDecimal kgscut;

    @ColumnAlias("CUTLCN")
    private String cutlcn;

    @ColumnAlias("GMTPERMAT")
    private BigDecimal gmtpermat;

    @ColumnAlias("PCSCUT")
    private BigDecimal pcscut;

    @ColumnAlias("REM")
    private String rem;

    @ColumnAlias("MAKIND")
    private String makind;

    @ColumnAlias("MAKLCN")
    private String maklcn;

    @ColumnAlias("FABRTO")
    private BigDecimal fabrto;

    @ColumnAlias("DYEJOB_TOTPCSCUT")
    private BigDecimal dyejobTotpcscut;

    @ColumnAlias("PCS1")
    private BigDecimal pcs1;

    @ColumnAlias("PCS2")
    private BigDecimal pcs2;

    @ColumnAlias("PCS3")
    private BigDecimal pcs3;

    @ColumnAlias("PCS4")
    private BigDecimal pcs4;

    @ColumnAlias("PCS5")
    private BigDecimal pcs5;

    @ColumnAlias("PCS6")
    private BigDecimal pcs6;

    @ColumnAlias("PCS7")
    private BigDecimal pcs7;

    @ColumnAlias("PCS8")
    private BigDecimal pcs8;

    @ColumnAlias("PCS9")
    private BigDecimal pcs9;

    @ColumnAlias("PCS10")
    private BigDecimal pcs10;

    @ColumnAlias("PCS11")
    private BigDecimal pcs11;

    @ColumnAlias("PCS12")
    private BigDecimal pcs12;

    @ColumnAlias("PCS13")
    private BigDecimal pcs13;

    @ColumnAlias("PCS14")
    private BigDecimal pcs14;

    @ColumnAlias("PCS15")
    private BigDecimal pcs15;

    @ColumnAlias("PCS16")
    private BigDecimal pcs16;

    @ColumnAlias("PCS17")
    private BigDecimal pcs17;

    @ColumnAlias("PCS18")
    private BigDecimal pcs18;

    @ColumnAlias("PCS19")
    private BigDecimal pcs19;

    @ColumnAlias("PCS20")
    private BigDecimal pcs20;

    @ColumnAlias("PCS21")
    private BigDecimal pcs21;

    @ColumnAlias("PCS22")
    private BigDecimal pcs22;

    @ColumnAlias("PCS23")
    private BigDecimal pcs23;

    @ColumnAlias("PCS24")
    private BigDecimal pcs24;

    @ColumnAlias("PCS25")
    private BigDecimal pcs25;

    @ColumnAlias("PCS26")
    private BigDecimal pcs26;

    @ColumnAlias("PCS27")
    private BigDecimal pcs27;

    @ColumnAlias("PCS28")
    private BigDecimal pcs28;

    @ColumnAlias("PCS29")
    private BigDecimal pcs29;

    @ColumnAlias("PCS30")
    private BigDecimal pcs30;

    @ColumnAlias("PCS31")
    private BigDecimal pcs31;

    @ColumnAlias("PCS32")
    private BigDecimal pcs32;

    @ColumnAlias("PCS33")
    private BigDecimal pcs33;

    @ColumnAlias("PCS34")
    private BigDecimal pcs34;

    @ColumnAlias("PCS35")
    private BigDecimal pcs35;

    @ColumnAlias("PCS36")
    private BigDecimal pcs36;

    @ColumnAlias("PCS37")
    private BigDecimal pcs37;

    @ColumnAlias("PCS38")
    private BigDecimal pcs38;

    @ColumnAlias("PCS39")
    private BigDecimal pcs39;

    @ColumnAlias("PCS40")
    private BigDecimal pcs40;

    @ColumnAlias("PCS41")
    private BigDecimal pcs41;

    @ColumnAlias("PCS42")
    private BigDecimal pcs42;

    @ColumnAlias("PCS43")
    private BigDecimal pcs43;

    @ColumnAlias("PCS44")
    private BigDecimal pcs44;

    @ColumnAlias("PCS45")
    private BigDecimal pcs45;

    @ColumnAlias("PCS46")
    private BigDecimal pcs46;

    @ColumnAlias("PCS47")
    private BigDecimal pcs47;

    @ColumnAlias("PCS48")
    private BigDecimal pcs48;

    @ColumnAlias("TOTAL_ORDER_PCSCUT")
    private BigDecimal totalOrderPcscut;

    @ColumnAlias("TOTAL_PCS1")
    private BigDecimal totalPcs1;

    @ColumnAlias("TOTAL_PCS2")
    private BigDecimal totalPcs2;

    @ColumnAlias("TOTAL_PCS3")
    private BigDecimal totalPcs3;

    @ColumnAlias("TOTAL_PCS4")
    private BigDecimal totalPcs4;

    @ColumnAlias("TOTAL_PCS5")
    private BigDecimal totalPcs5;

    @ColumnAlias("TOTAL_PCS6")
    private BigDecimal totalPcs6;

    @ColumnAlias("TOTAL_PCS7")
    private BigDecimal totalPcs7;

    @ColumnAlias("TOTAL_PCS8")
    private BigDecimal totalPcs8;

    @ColumnAlias("TOTAL_PCS9")
    private BigDecimal totalPcs9;

    @ColumnAlias("TOTAL_PCS10")
    private BigDecimal totalPcs10;

    @ColumnAlias("TOTAL_PCS11")
    private BigDecimal totalPcs11;

    @ColumnAlias("TOTAL_PCS12")
    private BigDecimal totalPcs12;

    @ColumnAlias("TOTAL_PCS13")
    private BigDecimal totalPcs13;

    @ColumnAlias("TOTAL_PCS14")
    private BigDecimal totalPcs14;

    @ColumnAlias("TOTAL_PCS15")
    private BigDecimal totalPcs15;

    @ColumnAlias("TOTAL_PCS16")
    private BigDecimal totalPcs16;

    @ColumnAlias("TOTAL_PCS17")
    private BigDecimal totalPcs17;

    @ColumnAlias("TOTAL_PCS18")
    private BigDecimal totalPcs18;

    @ColumnAlias("TOTAL_PCS19")
    private BigDecimal totalPcs19;

    @ColumnAlias("TOTAL_PCS20")
    private BigDecimal totalPcs20;

    @ColumnAlias("TOTAL_PCS21")
    private BigDecimal totalPcs21;

    @ColumnAlias("TOTAL_PCS22")
    private BigDecimal totalPcs22;

    @ColumnAlias("TOTAL_PCS23")
    private BigDecimal totalPcs23;

    @ColumnAlias("TOTAL_PCS24")
    private BigDecimal totalPcs24;

    @ColumnAlias("TOTAL_PCS25")
    private BigDecimal totalPcs25;

    @ColumnAlias("TOTAL_PCS26")
    private BigDecimal totalPcs26;

    @ColumnAlias("TOTAL_PCS27")
    private BigDecimal totalPcs27;

    @ColumnAlias("TOTAL_PCS28")
    private BigDecimal totalPcs28;

    @ColumnAlias("TOTAL_PCS29")
    private BigDecimal totalPcs29;

    @ColumnAlias("TOTAL_PCS30")
    private BigDecimal totalPcs30;

    @ColumnAlias("TOTAL_PCS31")
    private BigDecimal totalPcs31;

    @ColumnAlias("TOTAL_PCS32")
    private BigDecimal totalPcs32;

    @ColumnAlias("TOTAL_PCS33")
    private BigDecimal totalPcs33;

    @ColumnAlias("TOTAL_PCS34")
    private BigDecimal totalPcs34;

    @ColumnAlias("TOTAL_PCS35")
    private BigDecimal totalPcs35;

    @ColumnAlias("TOTAL_PCS36")
    private BigDecimal totalPcs36;

    @ColumnAlias("TOTAL_PCS37")
    private BigDecimal totalPcs37;

    @ColumnAlias("TOTAL_PCS38")
    private BigDecimal totalPcs38;

    @ColumnAlias("TOTAL_PCS39")
    private BigDecimal totalPcs39;

    @ColumnAlias("TOTAL_PCS40")
    private BigDecimal totalPcs40;

    @ColumnAlias("TOTAL_PCS41")
    private BigDecimal totalPcs41;

    @ColumnAlias("TOTAL_PCS42")
    private BigDecimal totalPcs42;

    @ColumnAlias("TOTAL_PCS43")
    private BigDecimal totalPcs43;

    @ColumnAlias("TOTAL_PCS44")
    private BigDecimal totalPcs44;

    @ColumnAlias("TOTAL_PCS45")
    private BigDecimal totalPcs45;

    @ColumnAlias("TOTAL_PCS46")
    private BigDecimal totalPcs46;

    @ColumnAlias("TOTAL_PCS47")
    private BigDecimal totalPcs47;

    @ColumnAlias("TOTAL_PCS48")
    private BigDecimal totalPcs48;

    @ColumnAlias("QTYORD1")
    private BigDecimal qtyord1;

    @ColumnAlias("QTYORD2")
    private BigDecimal qtyord2;

    @ColumnAlias("QTYORD3")
    private BigDecimal qtyord3;

    @ColumnAlias("QTYORD4")
    private BigDecimal qtyord4;

    @ColumnAlias("QTYORD5")
    private BigDecimal qtyord5;

    @ColumnAlias("QTYORD6")
    private BigDecimal qtyord6;

    @ColumnAlias("QTYORD7")
    private BigDecimal qtyord7;

    @ColumnAlias("QTYORD8")
    private BigDecimal qtyord8;

    @ColumnAlias("QTYORD9")
    private BigDecimal qtyord9;

    @ColumnAlias("QTYORD10")
    private BigDecimal qtyord10;

    @ColumnAlias("QTYORD11")
    private BigDecimal qtyord11;

    @ColumnAlias("QTYORD12")
    private BigDecimal qtyord12;

    @ColumnAlias("QTYORD13")
    private BigDecimal qtyord13;

    @ColumnAlias("QTYORD14")
    private BigDecimal qtyord14;

    @ColumnAlias("QTYORD15")
    private BigDecimal qtyord15;

    @ColumnAlias("QTYORD16")
    private BigDecimal qtyord16;

    @ColumnAlias("QTYORD17")
    private BigDecimal qtyord17;

    @ColumnAlias("QTYORD18")
    private BigDecimal qtyord18;

    @ColumnAlias("QTYORD19")
    private BigDecimal qtyord19;

    @ColumnAlias("QTYORD20")
    private BigDecimal qtyord20;

    @ColumnAlias("QTYORD21")
    private BigDecimal qtyord21;

    @ColumnAlias("QTYORD22")
    private BigDecimal qtyord22;

    @ColumnAlias("QTYORD23")
    private BigDecimal qtyord23;

    @ColumnAlias("QTYORD24")
    private BigDecimal qtyord24;

    @ColumnAlias("QTYORD25")
    private BigDecimal qtyord25;

    @ColumnAlias("QTYORD26")
    private BigDecimal qtyord26;

    @ColumnAlias("QTYORD27")
    private BigDecimal qtyord27;

    @ColumnAlias("QTYORD28")
    private BigDecimal qtyord28;

    @ColumnAlias("QTYORD29")
    private BigDecimal qtyord29;

    @ColumnAlias("QTYORD30")
    private BigDecimal qtyord30;

    @ColumnAlias("QTYORD31")
    private BigDecimal qtyord31;

    @ColumnAlias("QTYORD32")
    private BigDecimal qtyord32;

    @ColumnAlias("QTYORD33")
    private BigDecimal qtyord33;

    @ColumnAlias("QTYORD34")
    private BigDecimal qtyord34;

    @ColumnAlias("QTYORD35")
    private BigDecimal qtyord35;

    @ColumnAlias("QTYORD36")
    private BigDecimal qtyord36;

    @ColumnAlias("QTYORD37")
    private BigDecimal qtyord37;

    @ColumnAlias("QTYORD38")
    private BigDecimal qtyord38;

    @ColumnAlias("QTYORD39")
    private BigDecimal qtyord39;

    @ColumnAlias("QTYORD40")
    private BigDecimal qtyord40;

    @ColumnAlias("QTYORD41")
    private BigDecimal qtyord41;

    @ColumnAlias("QTYORD42")
    private BigDecimal qtyord42;

    @ColumnAlias("QTYORD43")
    private BigDecimal qtyord43;

    @ColumnAlias("QTYORD44")
    private BigDecimal qtyord44;

    @ColumnAlias("QTYORD45")
    private BigDecimal qtyord45;

    @ColumnAlias("QTYORD46")
    private BigDecimal qtyord46;

    @ColumnAlias("QTYORD47")
    private BigDecimal qtyord47;

    @ColumnAlias("QTYORD48")
    private BigDecimal qtyord48;

    @ColumnAlias("TOTPCS")
    private BigDecimal totpcs;

    @ColumnAlias("AVGCUTAVG")
    private BigDecimal avgcutavg;

    @ColumnAlias("AVGCUTAVG_FABCLR")
    private BigDecimal avgcutavgFabclr;

    @ColumnAlias("BAL1")
    private BigDecimal bal1;

    @ColumnAlias("BAL2")
    private BigDecimal bal2;

    @ColumnAlias("BAL3")
    private BigDecimal bal3;

    @ColumnAlias("BAL4")
    private BigDecimal bal4;

    @ColumnAlias("BAL5")
    private BigDecimal bal5;

    @ColumnAlias("BAL6")
    private BigDecimal bal6;

    @ColumnAlias("BAL7")
    private BigDecimal bal7;

    @ColumnAlias("BAL8")
    private BigDecimal bal8;

    @ColumnAlias("BAL9")
    private BigDecimal bal9;

    @ColumnAlias("BAL10")
    private BigDecimal bal10;

    @ColumnAlias("BAL11")
    private BigDecimal bal11;

    @ColumnAlias("BAL12")
    private BigDecimal bal12;

    @ColumnAlias("BAL13")
    private BigDecimal bal13;

    @ColumnAlias("BAL14")
    private BigDecimal bal14;

    @ColumnAlias("BAL15")
    private BigDecimal bal15;

    @ColumnAlias("BAL16")
    private BigDecimal bal16;

    @ColumnAlias("BAL17")
    private BigDecimal bal17;

    @ColumnAlias("BAL18")
    private BigDecimal bal18;

    @ColumnAlias("BAL19")
    private BigDecimal bal19;

    @ColumnAlias("BAL20")
    private BigDecimal bal20;

    @ColumnAlias("BAL21")
    private BigDecimal bal21;

    @ColumnAlias("BAL22")
    private BigDecimal bal22;

    @ColumnAlias("BAL23")
    private BigDecimal bal23;

    @ColumnAlias("BAL24")
    private BigDecimal bal24;

    @ColumnAlias("BAL25")
    private BigDecimal bal25;

    @ColumnAlias("BAL26")
    private BigDecimal bal26;

    @ColumnAlias("BAL27")
    private BigDecimal bal27;

    @ColumnAlias("BAL28")
    private BigDecimal bal28;

    @ColumnAlias("BAL29")
    private BigDecimal bal29;

    @ColumnAlias("BAL30")
    private BigDecimal bal30;

    @ColumnAlias("BAL31")
    private BigDecimal bal31;

    @ColumnAlias("BAL32")
    private BigDecimal bal32;

    @ColumnAlias("BAL33")
    private BigDecimal bal33;

    @ColumnAlias("BAL34")
    private BigDecimal bal34;

    @ColumnAlias("BAL35")
    private BigDecimal bal35;

    @ColumnAlias("BAL36")
    private BigDecimal bal36;

    @ColumnAlias("BAL37")
    private BigDecimal bal37;

    @ColumnAlias("BAL38")
    private BigDecimal bal38;

    @ColumnAlias("BAL39")
    private BigDecimal bal39;

    @ColumnAlias("BAL40")
    private BigDecimal bal40;

    @ColumnAlias("BAL41")
    private BigDecimal bal41;

    @ColumnAlias("BAL42")
    private BigDecimal bal42;

    @ColumnAlias("BAL43")
    private BigDecimal bal43;

    @ColumnAlias("BAL44")
    private BigDecimal bal44;

    @ColumnAlias("BAL45")
    private BigDecimal bal45;

    @ColumnAlias("BAL46")
    private BigDecimal bal46;

    @ColumnAlias("BAL47")
    private BigDecimal bal47;

    @ColumnAlias("BAL48")
    private BigDecimal bal48;

    @ColumnAlias("TOTBAL")
    private BigDecimal totbal;

    @ColumnAlias("COMP1")
    private BigDecimal comp1;

    @ColumnAlias("COMP2")
    private BigDecimal comp2;

    @ColumnAlias("COMP3")
    private BigDecimal comp3;

    @ColumnAlias("COMP4")
    private BigDecimal comp4;

    @ColumnAlias("COMP5")
    private BigDecimal comp5;

    @ColumnAlias("COMP6")
    private BigDecimal comp6;

    @ColumnAlias("COMP7")
    private BigDecimal comp7;

    @ColumnAlias("COMP8")
    private BigDecimal comp8;

    @ColumnAlias("COMP9")
    private BigDecimal comp9;

    @ColumnAlias("COMP10")
    private BigDecimal comp10;

    @ColumnAlias("COMP11")
    private BigDecimal comp11;

    @ColumnAlias("COMP12")
    private BigDecimal comp12;

    @ColumnAlias("COMP13")
    private BigDecimal comp13;

    @ColumnAlias("COMP14")
    private BigDecimal comp14;

    @ColumnAlias("COMP15")
    private BigDecimal comp15;

    @ColumnAlias("COMP16")
    private BigDecimal comp16;

    @ColumnAlias("COMP17")
    private BigDecimal comp17;

    @ColumnAlias("COMP18")
    private BigDecimal comp18;

    @ColumnAlias("COMP19")
    private BigDecimal comp19;

    @ColumnAlias("COMP20")
    private BigDecimal comp20;

    @ColumnAlias("COMP21")
    private BigDecimal comp21;

    @ColumnAlias("COMP22")
    private BigDecimal comp22;

    @ColumnAlias("COMP23")
    private BigDecimal comp23;

    @ColumnAlias("COMP24")
    private BigDecimal comp24;

    @ColumnAlias("COMP25")
    private BigDecimal comp25;

    @ColumnAlias("COMP26")
    private BigDecimal comp26;

    @ColumnAlias("COMP27")
    private BigDecimal comp27;

    @ColumnAlias("COMP28")
    private BigDecimal comp28;

    @ColumnAlias("COMP29")
    private BigDecimal comp29;

    @ColumnAlias("COMP30")
    private BigDecimal comp30;

    @ColumnAlias("COMP31")
    private BigDecimal comp31;

    @ColumnAlias("COMP32")
    private BigDecimal comp32;

    @ColumnAlias("COMP33")
    private BigDecimal comp33;

    @ColumnAlias("COMP34")
    private BigDecimal comp34;

    @ColumnAlias("COMP35")
    private BigDecimal comp35;

    @ColumnAlias("COMP36")
    private BigDecimal comp36;

    @ColumnAlias("COMP37")
    private BigDecimal comp37;

    @ColumnAlias("COMP38")
    private BigDecimal comp38;

    @ColumnAlias("COMP39")
    private BigDecimal comp39;

    @ColumnAlias("COMP40")
    private BigDecimal comp40;

    @ColumnAlias("COMP41")
    private BigDecimal comp41;

    @ColumnAlias("COMP42")
    private BigDecimal comp42;

    @ColumnAlias("COMP43")
    private BigDecimal comp43;

    @ColumnAlias("COMP44")
    private BigDecimal comp44;

    @ColumnAlias("COMP45")
    private BigDecimal comp45;

    @ColumnAlias("COMP46")
    private BigDecimal comp46;

    @ColumnAlias("COMP47")
    private BigDecimal comp47;

    @ColumnAlias("COMP48")
    private BigDecimal comp48;

    @ColumnAlias("TOTCOMP")
    private BigDecimal totcomp;

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public String getFabind() {
        return this.fabind;
    }

    public void setFabind(String fabind) {
        this.fabind = fabind;
    }

    public String getFabclrdes() {
        return this.fabclrdes;
    }

    public void setFabclrdes(String fabclrdes) {
        this.fabclrdes = fabclrdes;
    }

    public BigDecimal getCutseq() {
        return this.cutseq;
    }

    public void setCutseq(BigDecimal cutseq) {
        this.cutseq = cutseq;
    }

    public String getCutdate() {
        return this.cutdate;
    }

    public void setCutdate(String cutdate) {
        this.cutdate = cutdate;
    }

    public BigDecimal getKgs() {
        return this.kgs;
    }

    public void setKgs(BigDecimal kgs) {
        this.kgs = kgs;
    }

    public BigDecimal getCutavg() {
        return this.cutavg;
    }

    public void setCutavg(BigDecimal cutavg) {
        this.cutavg = cutavg;
    }

    public BigDecimal getKgscut() {
        return this.kgscut;
    }

    public void setKgscut(BigDecimal kgscut) {
        this.kgscut = kgscut;
    }

    public String getCutlcn() {
        return this.cutlcn;
    }

    public void setCutlcn(String cutlcn) {
        this.cutlcn = cutlcn;
    }

    public BigDecimal getGmtpermat() {
        return this.gmtpermat;
    }

    public void setGmtpermat(BigDecimal gmtpermat) {
        this.gmtpermat = gmtpermat;
    }

    public BigDecimal getPcscut() {
        return this.pcscut;
    }

    public void setPcscut(BigDecimal pcscut) {
        this.pcscut = pcscut;
    }

    public String getRem() {
        return this.rem;
    }

    public void setRem(String rem) {
        this.rem = rem;
    }

    public String getMakind() {
        return this.makind;
    }

    public void setMakind(String makind) {
        this.makind = makind;
    }

    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    public BigDecimal getFabrto() {
        return this.fabrto;
    }

    public void setFabrto(BigDecimal fabrto) {
        this.fabrto = fabrto;
    }

    public BigDecimal getDyejobTotpcscut() {
        return this.dyejobTotpcscut;
    }

    public void setDyejobTotpcscut(BigDecimal dyejobTotpcscut) {
        this.dyejobTotpcscut = dyejobTotpcscut;
    }

    public BigDecimal getPcs1() {
        return this.pcs1;
    }

    public void setPcs1(BigDecimal pcs1) {
        this.pcs1 = pcs1;
    }

    public BigDecimal getPcs2() {
        return this.pcs2;
    }

    public void setPcs2(BigDecimal pcs2) {
        this.pcs2 = pcs2;
    }

    public BigDecimal getPcs3() {
        return this.pcs3;
    }

    public void setPcs3(BigDecimal pcs3) {
        this.pcs3 = pcs3;
    }

    public BigDecimal getPcs4() {
        return this.pcs4;
    }

    public void setPcs4(BigDecimal pcs4) {
        this.pcs4 = pcs4;
    }

    public BigDecimal getPcs5() {
        return this.pcs5;
    }

    public void setPcs5(BigDecimal pcs5) {
        this.pcs5 = pcs5;
    }

    public BigDecimal getPcs6() {
        return this.pcs6;
    }

    public void setPcs6(BigDecimal pcs6) {
        this.pcs6 = pcs6;
    }

    public BigDecimal getPcs7() {
        return this.pcs7;
    }

    public void setPcs7(BigDecimal pcs7) {
        this.pcs7 = pcs7;
    }

    public BigDecimal getPcs8() {
        return this.pcs8;
    }

    public void setPcs8(BigDecimal pcs8) {
        this.pcs8 = pcs8;
    }

    public BigDecimal getPcs9() {
        return this.pcs9;
    }

    public void setPcs9(BigDecimal pcs9) {
        this.pcs9 = pcs9;
    }

    public BigDecimal getPcs10() {
        return this.pcs10;
    }

    public void setPcs10(BigDecimal pcs10) {
        this.pcs10 = pcs10;
    }

    public BigDecimal getPcs11() {
        return this.pcs11;
    }

    public void setPcs11(BigDecimal pcs11) {
        this.pcs11 = pcs11;
    }

    public BigDecimal getPcs12() {
        return this.pcs12;
    }

    public void setPcs12(BigDecimal pcs12) {
        this.pcs12 = pcs12;
    }

    public BigDecimal getPcs13() {
        return this.pcs13;
    }

    public void setPcs13(BigDecimal pcs13) {
        this.pcs13 = pcs13;
    }

    public BigDecimal getPcs14() {
        return this.pcs14;
    }

    public void setPcs14(BigDecimal pcs14) {
        this.pcs14 = pcs14;
    }

    public BigDecimal getPcs15() {
        return this.pcs15;
    }

    public void setPcs15(BigDecimal pcs15) {
        this.pcs15 = pcs15;
    }

    public BigDecimal getPcs16() {
        return this.pcs16;
    }

    public void setPcs16(BigDecimal pcs16) {
        this.pcs16 = pcs16;
    }

    public BigDecimal getPcs17() {
        return this.pcs17;
    }

    public void setPcs17(BigDecimal pcs17) {
        this.pcs17 = pcs17;
    }

    public BigDecimal getPcs18() {
        return this.pcs18;
    }

    public void setPcs18(BigDecimal pcs18) {
        this.pcs18 = pcs18;
    }

    public BigDecimal getPcs19() {
        return this.pcs19;
    }

    public void setPcs19(BigDecimal pcs19) {
        this.pcs19 = pcs19;
    }

    public BigDecimal getPcs20() {
        return this.pcs20;
    }

    public void setPcs20(BigDecimal pcs20) {
        this.pcs20 = pcs20;
    }

    public BigDecimal getPcs21() {
        return this.pcs21;
    }

    public void setPcs21(BigDecimal pcs21) {
        this.pcs21 = pcs21;
    }

    public BigDecimal getPcs22() {
        return this.pcs22;
    }

    public void setPcs22(BigDecimal pcs22) {
        this.pcs22 = pcs22;
    }

    public BigDecimal getPcs23() {
        return this.pcs23;
    }

    public void setPcs23(BigDecimal pcs23) {
        this.pcs23 = pcs23;
    }

    public BigDecimal getPcs24() {
        return this.pcs24;
    }

    public void setPcs24(BigDecimal pcs24) {
        this.pcs24 = pcs24;
    }

    public BigDecimal getPcs25() {
        return this.pcs25;
    }

    public void setPcs25(BigDecimal pcs25) {
        this.pcs25 = pcs25;
    }

    public BigDecimal getPcs26() {
        return this.pcs26;
    }

    public void setPcs26(BigDecimal pcs26) {
        this.pcs26 = pcs26;
    }

    public BigDecimal getPcs27() {
        return this.pcs27;
    }

    public void setPcs27(BigDecimal pcs27) {
        this.pcs27 = pcs27;
    }

    public BigDecimal getPcs28() {
        return this.pcs28;
    }

    public void setPcs28(BigDecimal pcs28) {
        this.pcs28 = pcs28;
    }

    public BigDecimal getPcs29() {
        return this.pcs29;
    }

    public void setPcs29(BigDecimal pcs29) {
        this.pcs29 = pcs29;
    }

    public BigDecimal getPcs30() {
        return this.pcs30;
    }

    public void setPcs30(BigDecimal pcs30) {
        this.pcs30 = pcs30;
    }

    public BigDecimal getPcs31() {
        return this.pcs31;
    }

    public void setPcs31(BigDecimal pcs31) {
        this.pcs31 = pcs31;
    }

    public BigDecimal getPcs32() {
        return this.pcs32;
    }

    public void setPcs32(BigDecimal pcs32) {
        this.pcs32 = pcs32;
    }

    public BigDecimal getPcs33() {
        return this.pcs33;
    }

    public void setPcs33(BigDecimal pcs33) {
        this.pcs33 = pcs33;
    }

    public BigDecimal getPcs34() {
        return this.pcs34;
    }

    public void setPcs34(BigDecimal pcs34) {
        this.pcs34 = pcs34;
    }

    public BigDecimal getPcs35() {
        return this.pcs35;
    }

    public void setPcs35(BigDecimal pcs35) {
        this.pcs35 = pcs35;
    }

    public BigDecimal getPcs36() {
        return this.pcs36;
    }

    public void setPcs36(BigDecimal pcs36) {
        this.pcs36 = pcs36;
    }

    public BigDecimal getPcs37() {
        return this.pcs37;
    }

    public void setPcs37(BigDecimal pcs37) {
        this.pcs37 = pcs37;
    }

    public BigDecimal getPcs38() {
        return this.pcs38;
    }

    public void setPcs38(BigDecimal pcs38) {
        this.pcs38 = pcs38;
    }

    public BigDecimal getPcs39() {
        return this.pcs39;
    }

    public void setPcs39(BigDecimal pcs39) {
        this.pcs39 = pcs39;
    }

    public BigDecimal getPcs40() {
        return this.pcs40;
    }

    public void setPcs40(BigDecimal pcs40) {
        this.pcs40 = pcs40;
    }

    public BigDecimal getPcs41() {
        return this.pcs41;
    }

    public void setPcs41(BigDecimal pcs41) {
        this.pcs41 = pcs41;
    }

    public BigDecimal getPcs42() {
        return this.pcs42;
    }

    public void setPcs42(BigDecimal pcs42) {
        this.pcs42 = pcs42;
    }

    public BigDecimal getPcs43() {
        return this.pcs43;
    }

    public void setPcs43(BigDecimal pcs43) {
        this.pcs43 = pcs43;
    }

    public BigDecimal getPcs44() {
        return this.pcs44;
    }

    public void setPcs44(BigDecimal pcs44) {
        this.pcs44 = pcs44;
    }

    public BigDecimal getPcs45() {
        return this.pcs45;
    }

    public void setPcs45(BigDecimal pcs45) {
        this.pcs45 = pcs45;
    }

    public BigDecimal getPcs46() {
        return this.pcs46;
    }

    public void setPcs46(BigDecimal pcs46) {
        this.pcs46 = pcs46;
    }

    public BigDecimal getPcs47() {
        return this.pcs47;
    }

    public void setPcs47(BigDecimal pcs47) {
        this.pcs47 = pcs47;
    }

    public BigDecimal getPcs48() {
        return this.pcs48;
    }

    public void setPcs48(BigDecimal pcs48) {
        this.pcs48 = pcs48;
    }

    public BigDecimal getTotalOrderPcscut() {
        return this.totalOrderPcscut;
    }

    public void setTotalOrderPcscut(BigDecimal totalOrderPcscut) {
        this.totalOrderPcscut = totalOrderPcscut;
    }

    public BigDecimal getTotalPcs1() {
        return this.totalPcs1;
    }

    public void setTotalPcs1(BigDecimal totalPcs1) {
        this.totalPcs1 = totalPcs1;
    }

    public BigDecimal getTotalPcs2() {
        return this.totalPcs2;
    }

    public void setTotalPcs2(BigDecimal totalPcs2) {
        this.totalPcs2 = totalPcs2;
    }

    public BigDecimal getTotalPcs3() {
        return this.totalPcs3;
    }

    public void setTotalPcs3(BigDecimal totalPcs3) {
        this.totalPcs3 = totalPcs3;
    }

    public BigDecimal getTotalPcs4() {
        return this.totalPcs4;
    }

    public void setTotalPcs4(BigDecimal totalPcs4) {
        this.totalPcs4 = totalPcs4;
    }

    public BigDecimal getTotalPcs5() {
        return this.totalPcs5;
    }

    public void setTotalPcs5(BigDecimal totalPcs5) {
        this.totalPcs5 = totalPcs5;
    }

    public BigDecimal getTotalPcs6() {
        return this.totalPcs6;
    }

    public void setTotalPcs6(BigDecimal totalPcs6) {
        this.totalPcs6 = totalPcs6;
    }

    public BigDecimal getTotalPcs7() {
        return this.totalPcs7;
    }

    public void setTotalPcs7(BigDecimal totalPcs7) {
        this.totalPcs7 = totalPcs7;
    }

    public BigDecimal getTotalPcs8() {
        return this.totalPcs8;
    }

    public void setTotalPcs8(BigDecimal totalPcs8) {
        this.totalPcs8 = totalPcs8;
    }

    public BigDecimal getTotalPcs9() {
        return this.totalPcs9;
    }

    public void setTotalPcs9(BigDecimal totalPcs9) {
        this.totalPcs9 = totalPcs9;
    }

    public BigDecimal getTotalPcs10() {
        return this.totalPcs10;
    }

    public void setTotalPcs10(BigDecimal totalPcs10) {
        this.totalPcs10 = totalPcs10;
    }

    public BigDecimal getTotalPcs11() {
        return this.totalPcs11;
    }

    public void setTotalPcs11(BigDecimal totalPcs11) {
        this.totalPcs11 = totalPcs11;
    }

    public BigDecimal getTotalPcs12() {
        return this.totalPcs12;
    }

    public void setTotalPcs12(BigDecimal totalPcs12) {
        this.totalPcs12 = totalPcs12;
    }

    public BigDecimal getTotalPcs13() {
        return this.totalPcs13;
    }

    public void setTotalPcs13(BigDecimal totalPcs13) {
        this.totalPcs13 = totalPcs13;
    }

    public BigDecimal getTotalPcs14() {
        return this.totalPcs14;
    }

    public void setTotalPcs14(BigDecimal totalPcs14) {
        this.totalPcs14 = totalPcs14;
    }

    public BigDecimal getTotalPcs15() {
        return this.totalPcs15;
    }

    public void setTotalPcs15(BigDecimal totalPcs15) {
        this.totalPcs15 = totalPcs15;
    }

    public BigDecimal getTotalPcs16() {
        return this.totalPcs16;
    }

    public void setTotalPcs16(BigDecimal totalPcs16) {
        this.totalPcs16 = totalPcs16;
    }

    public BigDecimal getTotalPcs17() {
        return this.totalPcs17;
    }

    public void setTotalPcs17(BigDecimal totalPcs17) {
        this.totalPcs17 = totalPcs17;
    }

    public BigDecimal getTotalPcs18() {
        return this.totalPcs18;
    }

    public void setTotalPcs18(BigDecimal totalPcs18) {
        this.totalPcs18 = totalPcs18;
    }

    public BigDecimal getTotalPcs19() {
        return this.totalPcs19;
    }

    public void setTotalPcs19(BigDecimal totalPcs19) {
        this.totalPcs19 = totalPcs19;
    }

    public BigDecimal getTotalPcs20() {
        return this.totalPcs20;
    }

    public void setTotalPcs20(BigDecimal totalPcs20) {
        this.totalPcs20 = totalPcs20;
    }

    public BigDecimal getTotalPcs21() {
        return this.totalPcs21;
    }

    public void setTotalPcs21(BigDecimal totalPcs21) {
        this.totalPcs21 = totalPcs21;
    }

    public BigDecimal getTotalPcs22() {
        return this.totalPcs22;
    }

    public void setTotalPcs22(BigDecimal totalPcs22) {
        this.totalPcs22 = totalPcs22;
    }

    public BigDecimal getTotalPcs23() {
        return this.totalPcs23;
    }

    public void setTotalPcs23(BigDecimal totalPcs23) {
        this.totalPcs23 = totalPcs23;
    }

    public BigDecimal getTotalPcs24() {
        return this.totalPcs24;
    }

    public void setTotalPcs24(BigDecimal totalPcs24) {
        this.totalPcs24 = totalPcs24;
    }

    public BigDecimal getTotalPcs25() {
        return this.totalPcs25;
    }

    public void setTotalPcs25(BigDecimal totalPcs25) {
        this.totalPcs25 = totalPcs25;
    }

    public BigDecimal getTotalPcs26() {
        return this.totalPcs26;
    }

    public void setTotalPcs26(BigDecimal totalPcs26) {
        this.totalPcs26 = totalPcs26;
    }

    public BigDecimal getTotalPcs27() {
        return this.totalPcs27;
    }

    public void setTotalPcs27(BigDecimal totalPcs27) {
        this.totalPcs27 = totalPcs27;
    }

    public BigDecimal getTotalPcs28() {
        return this.totalPcs28;
    }

    public void setTotalPcs28(BigDecimal totalPcs28) {
        this.totalPcs28 = totalPcs28;
    }

    public BigDecimal getTotalPcs29() {
        return this.totalPcs29;
    }

    public void setTotalPcs29(BigDecimal totalPcs29) {
        this.totalPcs29 = totalPcs29;
    }

    public BigDecimal getTotalPcs30() {
        return this.totalPcs30;
    }

    public void setTotalPcs30(BigDecimal totalPcs30) {
        this.totalPcs30 = totalPcs30;
    }

    public BigDecimal getTotalPcs31() {
        return this.totalPcs31;
    }

    public void setTotalPcs31(BigDecimal totalPcs31) {
        this.totalPcs31 = totalPcs31;
    }

    public BigDecimal getTotalPcs32() {
        return this.totalPcs32;
    }

    public void setTotalPcs32(BigDecimal totalPcs32) {
        this.totalPcs32 = totalPcs32;
    }

    public BigDecimal getTotalPcs33() {
        return this.totalPcs33;
    }

    public void setTotalPcs33(BigDecimal totalPcs33) {
        this.totalPcs33 = totalPcs33;
    }

    public BigDecimal getTotalPcs34() {
        return this.totalPcs34;
    }

    public void setTotalPcs34(BigDecimal totalPcs34) {
        this.totalPcs34 = totalPcs34;
    }

    public BigDecimal getTotalPcs35() {
        return this.totalPcs35;
    }

    public void setTotalPcs35(BigDecimal totalPcs35) {
        this.totalPcs35 = totalPcs35;
    }

    public BigDecimal getTotalPcs36() {
        return this.totalPcs36;
    }

    public void setTotalPcs36(BigDecimal totalPcs36) {
        this.totalPcs36 = totalPcs36;
    }

    public BigDecimal getTotalPcs37() {
        return this.totalPcs37;
    }

    public void setTotalPcs37(BigDecimal totalPcs37) {
        this.totalPcs37 = totalPcs37;
    }

    public BigDecimal getTotalPcs38() {
        return this.totalPcs38;
    }

    public void setTotalPcs38(BigDecimal totalPcs38) {
        this.totalPcs38 = totalPcs38;
    }

    public BigDecimal getTotalPcs39() {
        return this.totalPcs39;
    }

    public void setTotalPcs39(BigDecimal totalPcs39) {
        this.totalPcs39 = totalPcs39;
    }

    public BigDecimal getTotalPcs40() {
        return this.totalPcs40;
    }

    public void setTotalPcs40(BigDecimal totalPcs40) {
        this.totalPcs40 = totalPcs40;
    }

    public BigDecimal getTotalPcs41() {
        return this.totalPcs41;
    }

    public void setTotalPcs41(BigDecimal totalPcs41) {
        this.totalPcs41 = totalPcs41;
    }

    public BigDecimal getTotalPcs42() {
        return this.totalPcs42;
    }

    public void setTotalPcs42(BigDecimal totalPcs42) {
        this.totalPcs42 = totalPcs42;
    }

    public BigDecimal getTotalPcs43() {
        return this.totalPcs43;
    }

    public void setTotalPcs43(BigDecimal totalPcs43) {
        this.totalPcs43 = totalPcs43;
    }

    public BigDecimal getTotalPcs44() {
        return this.totalPcs44;
    }

    public void setTotalPcs44(BigDecimal totalPcs44) {
        this.totalPcs44 = totalPcs44;
    }

    public BigDecimal getTotalPcs45() {
        return this.totalPcs45;
    }

    public void setTotalPcs45(BigDecimal totalPcs45) {
        this.totalPcs45 = totalPcs45;
    }

    public BigDecimal getTotalPcs46() {
        return this.totalPcs46;
    }

    public void setTotalPcs46(BigDecimal totalPcs46) {
        this.totalPcs46 = totalPcs46;
    }

    public BigDecimal getTotalPcs47() {
        return this.totalPcs47;
    }

    public void setTotalPcs47(BigDecimal totalPcs47) {
        this.totalPcs47 = totalPcs47;
    }

    public BigDecimal getTotalPcs48() {
        return this.totalPcs48;
    }

    public void setTotalPcs48(BigDecimal totalPcs48) {
        this.totalPcs48 = totalPcs48;
    }

    public BigDecimal getQtyord1() {
        return this.qtyord1;
    }

    public void setQtyord1(BigDecimal qtyord1) {
        this.qtyord1 = qtyord1;
    }

    public BigDecimal getQtyord2() {
        return this.qtyord2;
    }

    public void setQtyord2(BigDecimal qtyord2) {
        this.qtyord2 = qtyord2;
    }

    public BigDecimal getQtyord3() {
        return this.qtyord3;
    }

    public void setQtyord3(BigDecimal qtyord3) {
        this.qtyord3 = qtyord3;
    }

    public BigDecimal getQtyord4() {
        return this.qtyord4;
    }

    public void setQtyord4(BigDecimal qtyord4) {
        this.qtyord4 = qtyord4;
    }

    public BigDecimal getQtyord5() {
        return this.qtyord5;
    }

    public void setQtyord5(BigDecimal qtyord5) {
        this.qtyord5 = qtyord5;
    }

    public BigDecimal getQtyord6() {
        return this.qtyord6;
    }

    public void setQtyord6(BigDecimal qtyord6) {
        this.qtyord6 = qtyord6;
    }

    public BigDecimal getQtyord7() {
        return this.qtyord7;
    }

    public void setQtyord7(BigDecimal qtyord7) {
        this.qtyord7 = qtyord7;
    }

    public BigDecimal getQtyord8() {
        return this.qtyord8;
    }

    public void setQtyord8(BigDecimal qtyord8) {
        this.qtyord8 = qtyord8;
    }

    public BigDecimal getQtyord9() {
        return this.qtyord9;
    }

    public void setQtyord9(BigDecimal qtyord9) {
        this.qtyord9 = qtyord9;
    }

    public BigDecimal getQtyord10() {
        return this.qtyord10;
    }

    public void setQtyord10(BigDecimal qtyord10) {
        this.qtyord10 = qtyord10;
    }

    public BigDecimal getQtyord11() {
        return this.qtyord11;
    }

    public void setQtyord11(BigDecimal qtyord11) {
        this.qtyord11 = qtyord11;
    }

    public BigDecimal getQtyord12() {
        return this.qtyord12;
    }

    public void setQtyord12(BigDecimal qtyord12) {
        this.qtyord12 = qtyord12;
    }

    public BigDecimal getQtyord13() {
        return this.qtyord13;
    }

    public void setQtyord13(BigDecimal qtyord13) {
        this.qtyord13 = qtyord13;
    }

    public BigDecimal getQtyord14() {
        return this.qtyord14;
    }

    public void setQtyord14(BigDecimal qtyord14) {
        this.qtyord14 = qtyord14;
    }

    public BigDecimal getQtyord15() {
        return this.qtyord15;
    }

    public void setQtyord15(BigDecimal qtyord15) {
        this.qtyord15 = qtyord15;
    }

    public BigDecimal getQtyord16() {
        return this.qtyord16;
    }

    public void setQtyord16(BigDecimal qtyord16) {
        this.qtyord16 = qtyord16;
    }

    public BigDecimal getQtyord17() {
        return this.qtyord17;
    }

    public void setQtyord17(BigDecimal qtyord17) {
        this.qtyord17 = qtyord17;
    }

    public BigDecimal getQtyord18() {
        return this.qtyord18;
    }

    public void setQtyord18(BigDecimal qtyord18) {
        this.qtyord18 = qtyord18;
    }

    public BigDecimal getQtyord19() {
        return this.qtyord19;
    }

    public void setQtyord19(BigDecimal qtyord19) {
        this.qtyord19 = qtyord19;
    }

    public BigDecimal getQtyord20() {
        return this.qtyord20;
    }

    public void setQtyord20(BigDecimal qtyord20) {
        this.qtyord20 = qtyord20;
    }

    public BigDecimal getQtyord21() {
        return this.qtyord21;
    }

    public void setQtyord21(BigDecimal qtyord21) {
        this.qtyord21 = qtyord21;
    }

    public BigDecimal getQtyord22() {
        return this.qtyord22;
    }

    public void setQtyord22(BigDecimal qtyord22) {
        this.qtyord22 = qtyord22;
    }

    public BigDecimal getQtyord23() {
        return this.qtyord23;
    }

    public void setQtyord23(BigDecimal qtyord23) {
        this.qtyord23 = qtyord23;
    }

    public BigDecimal getQtyord24() {
        return this.qtyord24;
    }

    public void setQtyord24(BigDecimal qtyord24) {
        this.qtyord24 = qtyord24;
    }

    public BigDecimal getQtyord25() {
        return this.qtyord25;
    }

    public void setQtyord25(BigDecimal qtyord25) {
        this.qtyord25 = qtyord25;
    }

    public BigDecimal getQtyord26() {
        return this.qtyord26;
    }

    public void setQtyord26(BigDecimal qtyord26) {
        this.qtyord26 = qtyord26;
    }

    public BigDecimal getQtyord27() {
        return this.qtyord27;
    }

    public void setQtyord27(BigDecimal qtyord27) {
        this.qtyord27 = qtyord27;
    }

    public BigDecimal getQtyord28() {
        return this.qtyord28;
    }

    public void setQtyord28(BigDecimal qtyord28) {
        this.qtyord28 = qtyord28;
    }

    public BigDecimal getQtyord29() {
        return this.qtyord29;
    }

    public void setQtyord29(BigDecimal qtyord29) {
        this.qtyord29 = qtyord29;
    }

    public BigDecimal getQtyord30() {
        return this.qtyord30;
    }

    public void setQtyord30(BigDecimal qtyord30) {
        this.qtyord30 = qtyord30;
    }

    public BigDecimal getQtyord31() {
        return this.qtyord31;
    }

    public void setQtyord31(BigDecimal qtyord31) {
        this.qtyord31 = qtyord31;
    }

    public BigDecimal getQtyord32() {
        return this.qtyord32;
    }

    public void setQtyord32(BigDecimal qtyord32) {
        this.qtyord32 = qtyord32;
    }

    public BigDecimal getQtyord33() {
        return this.qtyord33;
    }

    public void setQtyord33(BigDecimal qtyord33) {
        this.qtyord33 = qtyord33;
    }

    public BigDecimal getQtyord34() {
        return this.qtyord34;
    }

    public void setQtyord34(BigDecimal qtyord34) {
        this.qtyord34 = qtyord34;
    }

    public BigDecimal getQtyord35() {
        return this.qtyord35;
    }

    public void setQtyord35(BigDecimal qtyord35) {
        this.qtyord35 = qtyord35;
    }

    public BigDecimal getQtyord36() {
        return this.qtyord36;
    }

    public void setQtyord36(BigDecimal qtyord36) {
        this.qtyord36 = qtyord36;
    }

    public BigDecimal getQtyord37() {
        return this.qtyord37;
    }

    public void setQtyord37(BigDecimal qtyord37) {
        this.qtyord37 = qtyord37;
    }

    public BigDecimal getQtyord38() {
        return this.qtyord38;
    }

    public void setQtyord38(BigDecimal qtyord38) {
        this.qtyord38 = qtyord38;
    }

    public BigDecimal getQtyord39() {
        return this.qtyord39;
    }

    public void setQtyord39(BigDecimal qtyord39) {
        this.qtyord39 = qtyord39;
    }

    public BigDecimal getQtyord40() {
        return this.qtyord40;
    }

    public void setQtyord40(BigDecimal qtyord40) {
        this.qtyord40 = qtyord40;
    }

    public BigDecimal getQtyord41() {
        return this.qtyord41;
    }

    public void setQtyord41(BigDecimal qtyord41) {
        this.qtyord41 = qtyord41;
    }

    public BigDecimal getQtyord42() {
        return this.qtyord42;
    }

    public void setQtyord42(BigDecimal qtyord42) {
        this.qtyord42 = qtyord42;
    }

    public BigDecimal getQtyord43() {
        return this.qtyord43;
    }

    public void setQtyord43(BigDecimal qtyord43) {
        this.qtyord43 = qtyord43;
    }

    public BigDecimal getQtyord44() {
        return this.qtyord44;
    }

    public void setQtyord44(BigDecimal qtyord44) {
        this.qtyord44 = qtyord44;
    }

    public BigDecimal getQtyord45() {
        return this.qtyord45;
    }

    public void setQtyord45(BigDecimal qtyord45) {
        this.qtyord45 = qtyord45;
    }

    public BigDecimal getQtyord46() {
        return this.qtyord46;
    }

    public void setQtyord46(BigDecimal qtyord46) {
        this.qtyord46 = qtyord46;
    }

    public BigDecimal getQtyord47() {
        return this.qtyord47;
    }

    public void setQtyord47(BigDecimal qtyord47) {
        this.qtyord47 = qtyord47;
    }

    public BigDecimal getQtyord48() {
        return this.qtyord48;
    }

    public void setQtyord48(BigDecimal qtyord48) {
        this.qtyord48 = qtyord48;
    }

    public BigDecimal getTotpcs() {
        return this.totpcs;
    }

    public void setTotpcs(BigDecimal totpcs) {
        this.totpcs = totpcs;
    }

    public BigDecimal getAvgcutavg() {
        return this.avgcutavg;
    }

    public void setAvgcutavg(BigDecimal avgcutavg) {
        this.avgcutavg = avgcutavg;
    }

    public BigDecimal getAvgcutavgFabclr() {
        return this.avgcutavgFabclr;
    }

    public void setAvgcutavgFabclr(BigDecimal avgcutavgFabclr) {
        this.avgcutavgFabclr = avgcutavgFabclr;
    }

    public BigDecimal getBal1() {
        return this.bal1;
    }

    public void setBal1(BigDecimal bal1) {
        this.bal1 = bal1;
    }

    public BigDecimal getBal2() {
        return this.bal2;
    }

    public void setBal2(BigDecimal bal2) {
        this.bal2 = bal2;
    }

    public BigDecimal getBal3() {
        return this.bal3;
    }

    public void setBal3(BigDecimal bal3) {
        this.bal3 = bal3;
    }

    public BigDecimal getBal4() {
        return this.bal4;
    }

    public void setBal4(BigDecimal bal4) {
        this.bal4 = bal4;
    }

    public BigDecimal getBal5() {
        return this.bal5;
    }

    public void setBal5(BigDecimal bal5) {
        this.bal5 = bal5;
    }

    public BigDecimal getBal6() {
        return this.bal6;
    }

    public void setBal6(BigDecimal bal6) {
        this.bal6 = bal6;
    }

    public BigDecimal getBal7() {
        return this.bal7;
    }

    public void setBal7(BigDecimal bal7) {
        this.bal7 = bal7;
    }

    public BigDecimal getBal8() {
        return this.bal8;
    }

    public void setBal8(BigDecimal bal8) {
        this.bal8 = bal8;
    }

    public BigDecimal getBal9() {
        return this.bal9;
    }

    public void setBal9(BigDecimal bal9) {
        this.bal9 = bal9;
    }

    public BigDecimal getBal10() {
        return this.bal10;
    }

    public void setBal10(BigDecimal bal10) {
        this.bal10 = bal10;
    }

    public BigDecimal getBal11() {
        return this.bal11;
    }

    public void setBal11(BigDecimal bal11) {
        this.bal11 = bal11;
    }

    public BigDecimal getBal12() {
        return this.bal12;
    }

    public void setBal12(BigDecimal bal12) {
        this.bal12 = bal12;
    }

    public BigDecimal getBal13() {
        return this.bal13;
    }

    public void setBal13(BigDecimal bal13) {
        this.bal13 = bal13;
    }

    public BigDecimal getBal14() {
        return this.bal14;
    }

    public void setBal14(BigDecimal bal14) {
        this.bal14 = bal14;
    }

    public BigDecimal getBal15() {
        return this.bal15;
    }

    public void setBal15(BigDecimal bal15) {
        this.bal15 = bal15;
    }

    public BigDecimal getBal16() {
        return this.bal16;
    }

    public void setBal16(BigDecimal bal16) {
        this.bal16 = bal16;
    }

    public BigDecimal getBal17() {
        return this.bal17;
    }

    public void setBal17(BigDecimal bal17) {
        this.bal17 = bal17;
    }

    public BigDecimal getBal18() {
        return this.bal18;
    }

    public void setBal18(BigDecimal bal18) {
        this.bal18 = bal18;
    }

    public BigDecimal getBal19() {
        return this.bal19;
    }

    public void setBal19(BigDecimal bal19) {
        this.bal19 = bal19;
    }

    public BigDecimal getBal20() {
        return this.bal20;
    }

    public void setBal20(BigDecimal bal20) {
        this.bal20 = bal20;
    }

    public BigDecimal getBal21() {
        return this.bal21;
    }

    public void setBal21(BigDecimal bal21) {
        this.bal21 = bal21;
    }

    public BigDecimal getBal22() {
        return this.bal22;
    }

    public void setBal22(BigDecimal bal22) {
        this.bal22 = bal22;
    }

    public BigDecimal getBal23() {
        return this.bal23;
    }

    public void setBal23(BigDecimal bal23) {
        this.bal23 = bal23;
    }

    public BigDecimal getBal24() {
        return this.bal24;
    }

    public void setBal24(BigDecimal bal24) {
        this.bal24 = bal24;
    }

    public BigDecimal getBal25() {
        return this.bal25;
    }

    public void setBal25(BigDecimal bal25) {
        this.bal25 = bal25;
    }

    public BigDecimal getBal26() {
        return this.bal26;
    }

    public void setBal26(BigDecimal bal26) {
        this.bal26 = bal26;
    }

    public BigDecimal getBal27() {
        return this.bal27;
    }

    public void setBal27(BigDecimal bal27) {
        this.bal27 = bal27;
    }

    public BigDecimal getBal28() {
        return this.bal28;
    }

    public void setBal28(BigDecimal bal28) {
        this.bal28 = bal28;
    }

    public BigDecimal getBal29() {
        return this.bal29;
    }

    public void setBal29(BigDecimal bal29) {
        this.bal29 = bal29;
    }

    public BigDecimal getBal30() {
        return this.bal30;
    }

    public void setBal30(BigDecimal bal30) {
        this.bal30 = bal30;
    }

    public BigDecimal getBal31() {
        return this.bal31;
    }

    public void setBal31(BigDecimal bal31) {
        this.bal31 = bal31;
    }

    public BigDecimal getBal32() {
        return this.bal32;
    }

    public void setBal32(BigDecimal bal32) {
        this.bal32 = bal32;
    }

    public BigDecimal getBal33() {
        return this.bal33;
    }

    public void setBal33(BigDecimal bal33) {
        this.bal33 = bal33;
    }

    public BigDecimal getBal34() {
        return this.bal34;
    }

    public void setBal34(BigDecimal bal34) {
        this.bal34 = bal34;
    }

    public BigDecimal getBal35() {
        return this.bal35;
    }

    public void setBal35(BigDecimal bal35) {
        this.bal35 = bal35;
    }

    public BigDecimal getBal36() {
        return this.bal36;
    }

    public void setBal36(BigDecimal bal36) {
        this.bal36 = bal36;
    }

    public BigDecimal getBal37() {
        return this.bal37;
    }

    public void setBal37(BigDecimal bal37) {
        this.bal37 = bal37;
    }

    public BigDecimal getBal38() {
        return this.bal38;
    }

    public void setBal38(BigDecimal bal38) {
        this.bal38 = bal38;
    }

    public BigDecimal getBal39() {
        return this.bal39;
    }

    public void setBal39(BigDecimal bal39) {
        this.bal39 = bal39;
    }

    public BigDecimal getBal40() {
        return this.bal40;
    }

    public void setBal40(BigDecimal bal40) {
        this.bal40 = bal40;
    }

    public BigDecimal getBal41() {
        return this.bal41;
    }

    public void setBal41(BigDecimal bal41) {
        this.bal41 = bal41;
    }

    public BigDecimal getBal42() {
        return this.bal42;
    }

    public void setBal42(BigDecimal bal42) {
        this.bal42 = bal42;
    }

    public BigDecimal getBal43() {
        return this.bal43;
    }

    public void setBal43(BigDecimal bal43) {
        this.bal43 = bal43;
    }

    public BigDecimal getBal44() {
        return this.bal44;
    }

    public void setBal44(BigDecimal bal44) {
        this.bal44 = bal44;
    }

    public BigDecimal getBal45() {
        return this.bal45;
    }

    public void setBal45(BigDecimal bal45) {
        this.bal45 = bal45;
    }

    public BigDecimal getBal46() {
        return this.bal46;
    }

    public void setBal46(BigDecimal bal46) {
        this.bal46 = bal46;
    }

    public BigDecimal getBal47() {
        return this.bal47;
    }

    public void setBal47(BigDecimal bal47) {
        this.bal47 = bal47;
    }

    public BigDecimal getBal48() {
        return this.bal48;
    }

    public void setBal48(BigDecimal bal48) {
        this.bal48 = bal48;
    }

    public BigDecimal getTotbal() {
        return this.totbal;
    }

    public void setTotbal(BigDecimal totbal) {
        this.totbal = totbal;
    }

    public BigDecimal getComp1() {
        return this.comp1;
    }

    public void setComp1(BigDecimal comp1) {
        this.comp1 = comp1;
    }

    public BigDecimal getComp2() {
        return this.comp2;
    }

    public void setComp2(BigDecimal comp2) {
        this.comp2 = comp2;
    }

    public BigDecimal getComp3() {
        return this.comp3;
    }

    public void setComp3(BigDecimal comp3) {
        this.comp3 = comp3;
    }

    public BigDecimal getComp4() {
        return this.comp4;
    }

    public void setComp4(BigDecimal comp4) {
        this.comp4 = comp4;
    }

    public BigDecimal getComp5() {
        return this.comp5;
    }

    public void setComp5(BigDecimal comp5) {
        this.comp5 = comp5;
    }

    public BigDecimal getComp6() {
        return this.comp6;
    }

    public void setComp6(BigDecimal comp6) {
        this.comp6 = comp6;
    }

    public BigDecimal getComp7() {
        return this.comp7;
    }

    public void setComp7(BigDecimal comp7) {
        this.comp7 = comp7;
    }

    public BigDecimal getComp8() {
        return this.comp8;
    }

    public void setComp8(BigDecimal comp8) {
        this.comp8 = comp8;
    }

    public BigDecimal getComp9() {
        return this.comp9;
    }

    public void setComp9(BigDecimal comp9) {
        this.comp9 = comp9;
    }

    public BigDecimal getComp10() {
        return this.comp10;
    }

    public void setComp10(BigDecimal comp10) {
        this.comp10 = comp10;
    }

    public BigDecimal getComp11() {
        return this.comp11;
    }

    public void setComp11(BigDecimal comp11) {
        this.comp11 = comp11;
    }

    public BigDecimal getComp12() {
        return this.comp12;
    }

    public void setComp12(BigDecimal comp12) {
        this.comp12 = comp12;
    }

    public BigDecimal getComp13() {
        return this.comp13;
    }

    public void setComp13(BigDecimal comp13) {
        this.comp13 = comp13;
    }

    public BigDecimal getComp14() {
        return this.comp14;
    }

    public void setComp14(BigDecimal comp14) {
        this.comp14 = comp14;
    }

    public BigDecimal getComp15() {
        return this.comp15;
    }

    public void setComp15(BigDecimal comp15) {
        this.comp15 = comp15;
    }

    public BigDecimal getComp16() {
        return this.comp16;
    }

    public void setComp16(BigDecimal comp16) {
        this.comp16 = comp16;
    }

    public BigDecimal getComp17() {
        return this.comp17;
    }

    public void setComp17(BigDecimal comp17) {
        this.comp17 = comp17;
    }

    public BigDecimal getComp18() {
        return this.comp18;
    }

    public void setComp18(BigDecimal comp18) {
        this.comp18 = comp18;
    }

    public BigDecimal getComp19() {
        return this.comp19;
    }

    public void setComp19(BigDecimal comp19) {
        this.comp19 = comp19;
    }

    public BigDecimal getComp20() {
        return this.comp20;
    }

    public void setComp20(BigDecimal comp20) {
        this.comp20 = comp20;
    }

    public BigDecimal getComp21() {
        return this.comp21;
    }

    public void setComp21(BigDecimal comp21) {
        this.comp21 = comp21;
    }

    public BigDecimal getComp22() {
        return this.comp22;
    }

    public void setComp22(BigDecimal comp22) {
        this.comp22 = comp22;
    }

    public BigDecimal getComp23() {
        return this.comp23;
    }

    public void setComp23(BigDecimal comp23) {
        this.comp23 = comp23;
    }

    public BigDecimal getComp24() {
        return this.comp24;
    }

    public void setComp24(BigDecimal comp24) {
        this.comp24 = comp24;
    }

    public BigDecimal getComp25() {
        return this.comp25;
    }

    public void setComp25(BigDecimal comp25) {
        this.comp25 = comp25;
    }

    public BigDecimal getComp26() {
        return this.comp26;
    }

    public void setComp26(BigDecimal comp26) {
        this.comp26 = comp26;
    }

    public BigDecimal getComp27() {
        return this.comp27;
    }

    public void setComp27(BigDecimal comp27) {
        this.comp27 = comp27;
    }

    public BigDecimal getComp28() {
        return this.comp28;
    }

    public void setComp28(BigDecimal comp28) {
        this.comp28 = comp28;
    }

    public BigDecimal getComp29() {
        return this.comp29;
    }

    public void setComp29(BigDecimal comp29) {
        this.comp29 = comp29;
    }

    public BigDecimal getComp30() {
        return this.comp30;
    }

    public void setComp30(BigDecimal comp30) {
        this.comp30 = comp30;
    }

    public BigDecimal getComp31() {
        return this.comp31;
    }

    public void setComp31(BigDecimal comp31) {
        this.comp31 = comp31;
    }

    public BigDecimal getComp32() {
        return this.comp32;
    }

    public void setComp32(BigDecimal comp32) {
        this.comp32 = comp32;
    }

    public BigDecimal getComp33() {
        return this.comp33;
    }

    public void setComp33(BigDecimal comp33) {
        this.comp33 = comp33;
    }

    public BigDecimal getComp34() {
        return this.comp34;
    }

    public void setComp34(BigDecimal comp34) {
        this.comp34 = comp34;
    }

    public BigDecimal getComp35() {
        return this.comp35;
    }

    public void setComp35(BigDecimal comp35) {
        this.comp35 = comp35;
    }

    public BigDecimal getComp36() {
        return this.comp36;
    }

    public void setComp36(BigDecimal comp36) {
        this.comp36 = comp36;
    }

    public BigDecimal getComp37() {
        return this.comp37;
    }

    public void setComp37(BigDecimal comp37) {
        this.comp37 = comp37;
    }

    public BigDecimal getComp38() {
        return this.comp38;
    }

    public void setComp38(BigDecimal comp38) {
        this.comp38 = comp38;
    }

    public BigDecimal getComp39() {
        return this.comp39;
    }

    public void setComp39(BigDecimal comp39) {
        this.comp39 = comp39;
    }

    public BigDecimal getComp40() {
        return this.comp40;
    }

    public void setComp40(BigDecimal comp40) {
        this.comp40 = comp40;
    }

    public BigDecimal getComp41() {
        return this.comp41;
    }

    public void setComp41(BigDecimal comp41) {
        this.comp41 = comp41;
    }

    public BigDecimal getComp42() {
        return this.comp42;
    }

    public void setComp42(BigDecimal comp42) {
        this.comp42 = comp42;
    }

    public BigDecimal getComp43() {
        return this.comp43;
    }

    public void setComp43(BigDecimal comp43) {
        this.comp43 = comp43;
    }

    public BigDecimal getComp44() {
        return this.comp44;
    }

    public void setComp44(BigDecimal comp44) {
        this.comp44 = comp44;
    }

    public BigDecimal getComp45() {
        return this.comp45;
    }

    public void setComp45(BigDecimal comp45) {
        this.comp45 = comp45;
    }

    public BigDecimal getComp46() {
        return this.comp46;
    }

    public void setComp46(BigDecimal comp46) {
        this.comp46 = comp46;
    }

    public BigDecimal getComp47() {
        return this.comp47;
    }

    public void setComp47(BigDecimal comp47) {
        this.comp47 = comp47;
    }

    public BigDecimal getComp48() {
        return this.comp48;
    }

    public void setComp48(BigDecimal comp48) {
        this.comp48 = comp48;
    }

    public BigDecimal getTotcomp() {
        return this.totcomp;
    }

    public void setTotcomp(BigDecimal totcomp) {
        this.totcomp = totcomp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize)) return false;
        final ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize procCu1000pk0qryCuttingBySizeResponsePoutCutbySize = (ProcCu1000pk0QryCuttingBySizeResponsePoutCutbySize) o;
        return Objects.equals(getDyejob(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getDyejob()) &&
                Objects.equals(getFabseq(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getFabseq()) &&
                Objects.equals(getFabtyp(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getFabtyp()) &&
                Objects.equals(getFabind(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getFabind()) &&
                Objects.equals(getFabclrdes(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getFabclrdes()) &&
                Objects.equals(getCutseq(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getCutseq()) &&
                Objects.equals(getCutdate(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getCutdate()) &&
                Objects.equals(getKgs(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getKgs()) &&
                Objects.equals(getCutavg(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getCutavg()) &&
                Objects.equals(getKgscut(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getKgscut()) &&
                Objects.equals(getCutlcn(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getCutlcn()) &&
                Objects.equals(getGmtpermat(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getGmtpermat()) &&
                Objects.equals(getPcscut(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcscut()) &&
                Objects.equals(getRem(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getRem()) &&
                Objects.equals(getMakind(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getMakind()) &&
                Objects.equals(getMaklcn(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getMaklcn()) &&
                Objects.equals(getFabrto(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getFabrto()) &&
                Objects.equals(getDyejobTotpcscut(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getDyejobTotpcscut()) &&
                Objects.equals(getPcs1(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs1()) &&
                Objects.equals(getPcs2(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs2()) &&
                Objects.equals(getPcs3(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs3()) &&
                Objects.equals(getPcs4(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs4()) &&
                Objects.equals(getPcs5(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs5()) &&
                Objects.equals(getPcs6(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs6()) &&
                Objects.equals(getPcs7(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs7()) &&
                Objects.equals(getPcs8(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs8()) &&
                Objects.equals(getPcs9(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs9()) &&
                Objects.equals(getPcs10(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs10()) &&
                Objects.equals(getPcs11(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs11()) &&
                Objects.equals(getPcs12(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs12()) &&
                Objects.equals(getPcs13(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs13()) &&
                Objects.equals(getPcs14(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs14()) &&
                Objects.equals(getPcs15(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs15()) &&
                Objects.equals(getPcs16(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs16()) &&
                Objects.equals(getPcs17(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs17()) &&
                Objects.equals(getPcs18(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs18()) &&
                Objects.equals(getPcs19(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs19()) &&
                Objects.equals(getPcs20(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs20()) &&
                Objects.equals(getPcs21(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs21()) &&
                Objects.equals(getPcs22(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs22()) &&
                Objects.equals(getPcs23(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs23()) &&
                Objects.equals(getPcs24(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs24()) &&
                Objects.equals(getPcs25(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs25()) &&
                Objects.equals(getPcs26(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs26()) &&
                Objects.equals(getPcs27(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs27()) &&
                Objects.equals(getPcs28(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs28()) &&
                Objects.equals(getPcs29(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs29()) &&
                Objects.equals(getPcs30(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs30()) &&
                Objects.equals(getPcs31(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs31()) &&
                Objects.equals(getPcs32(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs32()) &&
                Objects.equals(getPcs33(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs33()) &&
                Objects.equals(getPcs34(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs34()) &&
                Objects.equals(getPcs35(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs35()) &&
                Objects.equals(getPcs36(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs36()) &&
                Objects.equals(getPcs37(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs37()) &&
                Objects.equals(getPcs38(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs38()) &&
                Objects.equals(getPcs39(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs39()) &&
                Objects.equals(getPcs40(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs40()) &&
                Objects.equals(getPcs41(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs41()) &&
                Objects.equals(getPcs42(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs42()) &&
                Objects.equals(getPcs43(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs43()) &&
                Objects.equals(getPcs44(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs44()) &&
                Objects.equals(getPcs45(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs45()) &&
                Objects.equals(getPcs46(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs46()) &&
                Objects.equals(getPcs47(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs47()) &&
                Objects.equals(getPcs48(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getPcs48()) &&
                Objects.equals(getTotalOrderPcscut(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalOrderPcscut()) &&
                Objects.equals(getTotalPcs1(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs1()) &&
                Objects.equals(getTotalPcs2(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs2()) &&
                Objects.equals(getTotalPcs3(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs3()) &&
                Objects.equals(getTotalPcs4(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs4()) &&
                Objects.equals(getTotalPcs5(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs5()) &&
                Objects.equals(getTotalPcs6(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs6()) &&
                Objects.equals(getTotalPcs7(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs7()) &&
                Objects.equals(getTotalPcs8(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs8()) &&
                Objects.equals(getTotalPcs9(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs9()) &&
                Objects.equals(getTotalPcs10(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs10()) &&
                Objects.equals(getTotalPcs11(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs11()) &&
                Objects.equals(getTotalPcs12(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs12()) &&
                Objects.equals(getTotalPcs13(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs13()) &&
                Objects.equals(getTotalPcs14(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs14()) &&
                Objects.equals(getTotalPcs15(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs15()) &&
                Objects.equals(getTotalPcs16(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs16()) &&
                Objects.equals(getTotalPcs17(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs17()) &&
                Objects.equals(getTotalPcs18(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs18()) &&
                Objects.equals(getTotalPcs19(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs19()) &&
                Objects.equals(getTotalPcs20(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs20()) &&
                Objects.equals(getTotalPcs21(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs21()) &&
                Objects.equals(getTotalPcs22(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs22()) &&
                Objects.equals(getTotalPcs23(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs23()) &&
                Objects.equals(getTotalPcs24(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs24()) &&
                Objects.equals(getTotalPcs25(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs25()) &&
                Objects.equals(getTotalPcs26(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs26()) &&
                Objects.equals(getTotalPcs27(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs27()) &&
                Objects.equals(getTotalPcs28(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs28()) &&
                Objects.equals(getTotalPcs29(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs29()) &&
                Objects.equals(getTotalPcs30(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs30()) &&
                Objects.equals(getTotalPcs31(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs31()) &&
                Objects.equals(getTotalPcs32(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs32()) &&
                Objects.equals(getTotalPcs33(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs33()) &&
                Objects.equals(getTotalPcs34(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs34()) &&
                Objects.equals(getTotalPcs35(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs35()) &&
                Objects.equals(getTotalPcs36(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs36()) &&
                Objects.equals(getTotalPcs37(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs37()) &&
                Objects.equals(getTotalPcs38(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs38()) &&
                Objects.equals(getTotalPcs39(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs39()) &&
                Objects.equals(getTotalPcs40(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs40()) &&
                Objects.equals(getTotalPcs41(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs41()) &&
                Objects.equals(getTotalPcs42(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs42()) &&
                Objects.equals(getTotalPcs43(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs43()) &&
                Objects.equals(getTotalPcs44(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs44()) &&
                Objects.equals(getTotalPcs45(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs45()) &&
                Objects.equals(getTotalPcs46(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs46()) &&
                Objects.equals(getTotalPcs47(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs47()) &&
                Objects.equals(getTotalPcs48(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotalPcs48()) &&
                Objects.equals(getQtyord1(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord1()) &&
                Objects.equals(getQtyord2(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord2()) &&
                Objects.equals(getQtyord3(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord3()) &&
                Objects.equals(getQtyord4(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord4()) &&
                Objects.equals(getQtyord5(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord5()) &&
                Objects.equals(getQtyord6(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord6()) &&
                Objects.equals(getQtyord7(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord7()) &&
                Objects.equals(getQtyord8(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord8()) &&
                Objects.equals(getQtyord9(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord9()) &&
                Objects.equals(getQtyord10(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord10()) &&
                Objects.equals(getQtyord11(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord11()) &&
                Objects.equals(getQtyord12(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord12()) &&
                Objects.equals(getQtyord13(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord13()) &&
                Objects.equals(getQtyord14(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord14()) &&
                Objects.equals(getQtyord15(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord15()) &&
                Objects.equals(getQtyord16(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord16()) &&
                Objects.equals(getQtyord17(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord17()) &&
                Objects.equals(getQtyord18(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord18()) &&
                Objects.equals(getQtyord19(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord19()) &&
                Objects.equals(getQtyord20(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord20()) &&
                Objects.equals(getQtyord21(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord21()) &&
                Objects.equals(getQtyord22(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord22()) &&
                Objects.equals(getQtyord23(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord23()) &&
                Objects.equals(getQtyord24(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord24()) &&
                Objects.equals(getQtyord25(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord25()) &&
                Objects.equals(getQtyord26(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord26()) &&
                Objects.equals(getQtyord27(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord27()) &&
                Objects.equals(getQtyord28(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord28()) &&
                Objects.equals(getQtyord29(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord29()) &&
                Objects.equals(getQtyord30(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord30()) &&
                Objects.equals(getQtyord31(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord31()) &&
                Objects.equals(getQtyord32(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord32()) &&
                Objects.equals(getQtyord33(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord33()) &&
                Objects.equals(getQtyord34(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord34()) &&
                Objects.equals(getQtyord35(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord35()) &&
                Objects.equals(getQtyord36(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord36()) &&
                Objects.equals(getQtyord37(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord37()) &&
                Objects.equals(getQtyord38(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord38()) &&
                Objects.equals(getQtyord39(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord39()) &&
                Objects.equals(getQtyord40(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord40()) &&
                Objects.equals(getQtyord41(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord41()) &&
                Objects.equals(getQtyord42(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord42()) &&
                Objects.equals(getQtyord43(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord43()) &&
                Objects.equals(getQtyord44(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord44()) &&
                Objects.equals(getQtyord45(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord45()) &&
                Objects.equals(getQtyord46(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord46()) &&
                Objects.equals(getQtyord47(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord47()) &&
                Objects.equals(getQtyord48(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getQtyord48()) &&
                Objects.equals(getTotpcs(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotpcs()) &&
                Objects.equals(getAvgcutavg(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getAvgcutavg()) &&
                Objects.equals(getAvgcutavgFabclr(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getAvgcutavgFabclr()) &&
                Objects.equals(getBal1(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal1()) &&
                Objects.equals(getBal2(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal2()) &&
                Objects.equals(getBal3(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal3()) &&
                Objects.equals(getBal4(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal4()) &&
                Objects.equals(getBal5(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal5()) &&
                Objects.equals(getBal6(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal6()) &&
                Objects.equals(getBal7(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal7()) &&
                Objects.equals(getBal8(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal8()) &&
                Objects.equals(getBal9(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal9()) &&
                Objects.equals(getBal10(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal10()) &&
                Objects.equals(getBal11(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal11()) &&
                Objects.equals(getBal12(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal12()) &&
                Objects.equals(getBal13(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal13()) &&
                Objects.equals(getBal14(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal14()) &&
                Objects.equals(getBal15(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal15()) &&
                Objects.equals(getBal16(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal16()) &&
                Objects.equals(getBal17(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal17()) &&
                Objects.equals(getBal18(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal18()) &&
                Objects.equals(getBal19(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal19()) &&
                Objects.equals(getBal20(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal20()) &&
                Objects.equals(getBal21(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal21()) &&
                Objects.equals(getBal22(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal22()) &&
                Objects.equals(getBal23(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal23()) &&
                Objects.equals(getBal24(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal24()) &&
                Objects.equals(getBal25(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal25()) &&
                Objects.equals(getBal26(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal26()) &&
                Objects.equals(getBal27(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal27()) &&
                Objects.equals(getBal28(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal28()) &&
                Objects.equals(getBal29(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal29()) &&
                Objects.equals(getBal30(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal30()) &&
                Objects.equals(getBal31(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal31()) &&
                Objects.equals(getBal32(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal32()) &&
                Objects.equals(getBal33(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal33()) &&
                Objects.equals(getBal34(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal34()) &&
                Objects.equals(getBal35(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal35()) &&
                Objects.equals(getBal36(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal36()) &&
                Objects.equals(getBal37(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal37()) &&
                Objects.equals(getBal38(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal38()) &&
                Objects.equals(getBal39(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal39()) &&
                Objects.equals(getBal40(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal40()) &&
                Objects.equals(getBal41(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal41()) &&
                Objects.equals(getBal42(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal42()) &&
                Objects.equals(getBal43(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal43()) &&
                Objects.equals(getBal44(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal44()) &&
                Objects.equals(getBal45(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal45()) &&
                Objects.equals(getBal46(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal46()) &&
                Objects.equals(getBal47(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal47()) &&
                Objects.equals(getBal48(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getBal48()) &&
                Objects.equals(getTotbal(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotbal()) &&
                Objects.equals(getComp1(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp1()) &&
                Objects.equals(getComp2(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp2()) &&
                Objects.equals(getComp3(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp3()) &&
                Objects.equals(getComp4(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp4()) &&
                Objects.equals(getComp5(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp5()) &&
                Objects.equals(getComp6(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp6()) &&
                Objects.equals(getComp7(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp7()) &&
                Objects.equals(getComp8(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp8()) &&
                Objects.equals(getComp9(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp9()) &&
                Objects.equals(getComp10(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp10()) &&
                Objects.equals(getComp11(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp11()) &&
                Objects.equals(getComp12(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp12()) &&
                Objects.equals(getComp13(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp13()) &&
                Objects.equals(getComp14(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp14()) &&
                Objects.equals(getComp15(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp15()) &&
                Objects.equals(getComp16(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp16()) &&
                Objects.equals(getComp17(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp17()) &&
                Objects.equals(getComp18(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp18()) &&
                Objects.equals(getComp19(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp19()) &&
                Objects.equals(getComp20(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp20()) &&
                Objects.equals(getComp21(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp21()) &&
                Objects.equals(getComp22(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp22()) &&
                Objects.equals(getComp23(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp23()) &&
                Objects.equals(getComp24(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp24()) &&
                Objects.equals(getComp25(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp25()) &&
                Objects.equals(getComp26(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp26()) &&
                Objects.equals(getComp27(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp27()) &&
                Objects.equals(getComp28(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp28()) &&
                Objects.equals(getComp29(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp29()) &&
                Objects.equals(getComp30(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp30()) &&
                Objects.equals(getComp31(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp31()) &&
                Objects.equals(getComp32(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp32()) &&
                Objects.equals(getComp33(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp33()) &&
                Objects.equals(getComp34(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp34()) &&
                Objects.equals(getComp35(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp35()) &&
                Objects.equals(getComp36(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp36()) &&
                Objects.equals(getComp37(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp37()) &&
                Objects.equals(getComp38(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp38()) &&
                Objects.equals(getComp39(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp39()) &&
                Objects.equals(getComp40(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp40()) &&
                Objects.equals(getComp41(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp41()) &&
                Objects.equals(getComp42(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp42()) &&
                Objects.equals(getComp43(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp43()) &&
                Objects.equals(getComp44(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp44()) &&
                Objects.equals(getComp45(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp45()) &&
                Objects.equals(getComp46(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp46()) &&
                Objects.equals(getComp47(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp47()) &&
                Objects.equals(getComp48(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getComp48()) &&
                Objects.equals(getTotcomp(), procCu1000pk0qryCuttingBySizeResponsePoutCutbySize.getTotcomp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDyejob(),
                getFabseq(),
                getFabtyp(),
                getFabind(),
                getFabclrdes(),
                getCutseq(),
                getCutdate(),
                getKgs(),
                getCutavg(),
                getKgscut(),
                getCutlcn(),
                getGmtpermat(),
                getPcscut(),
                getRem(),
                getMakind(),
                getMaklcn(),
                getFabrto(),
                getDyejobTotpcscut(),
                getPcs1(),
                getPcs2(),
                getPcs3(),
                getPcs4(),
                getPcs5(),
                getPcs6(),
                getPcs7(),
                getPcs8(),
                getPcs9(),
                getPcs10(),
                getPcs11(),
                getPcs12(),
                getPcs13(),
                getPcs14(),
                getPcs15(),
                getPcs16(),
                getPcs17(),
                getPcs18(),
                getPcs19(),
                getPcs20(),
                getPcs21(),
                getPcs22(),
                getPcs23(),
                getPcs24(),
                getPcs25(),
                getPcs26(),
                getPcs27(),
                getPcs28(),
                getPcs29(),
                getPcs30(),
                getPcs31(),
                getPcs32(),
                getPcs33(),
                getPcs34(),
                getPcs35(),
                getPcs36(),
                getPcs37(),
                getPcs38(),
                getPcs39(),
                getPcs40(),
                getPcs41(),
                getPcs42(),
                getPcs43(),
                getPcs44(),
                getPcs45(),
                getPcs46(),
                getPcs47(),
                getPcs48(),
                getTotalOrderPcscut(),
                getTotalPcs1(),
                getTotalPcs2(),
                getTotalPcs3(),
                getTotalPcs4(),
                getTotalPcs5(),
                getTotalPcs6(),
                getTotalPcs7(),
                getTotalPcs8(),
                getTotalPcs9(),
                getTotalPcs10(),
                getTotalPcs11(),
                getTotalPcs12(),
                getTotalPcs13(),
                getTotalPcs14(),
                getTotalPcs15(),
                getTotalPcs16(),
                getTotalPcs17(),
                getTotalPcs18(),
                getTotalPcs19(),
                getTotalPcs20(),
                getTotalPcs21(),
                getTotalPcs22(),
                getTotalPcs23(),
                getTotalPcs24(),
                getTotalPcs25(),
                getTotalPcs26(),
                getTotalPcs27(),
                getTotalPcs28(),
                getTotalPcs29(),
                getTotalPcs30(),
                getTotalPcs31(),
                getTotalPcs32(),
                getTotalPcs33(),
                getTotalPcs34(),
                getTotalPcs35(),
                getTotalPcs36(),
                getTotalPcs37(),
                getTotalPcs38(),
                getTotalPcs39(),
                getTotalPcs40(),
                getTotalPcs41(),
                getTotalPcs42(),
                getTotalPcs43(),
                getTotalPcs44(),
                getTotalPcs45(),
                getTotalPcs46(),
                getTotalPcs47(),
                getTotalPcs48(),
                getQtyord1(),
                getQtyord2(),
                getQtyord3(),
                getQtyord4(),
                getQtyord5(),
                getQtyord6(),
                getQtyord7(),
                getQtyord8(),
                getQtyord9(),
                getQtyord10(),
                getQtyord11(),
                getQtyord12(),
                getQtyord13(),
                getQtyord14(),
                getQtyord15(),
                getQtyord16(),
                getQtyord17(),
                getQtyord18(),
                getQtyord19(),
                getQtyord20(),
                getQtyord21(),
                getQtyord22(),
                getQtyord23(),
                getQtyord24(),
                getQtyord25(),
                getQtyord26(),
                getQtyord27(),
                getQtyord28(),
                getQtyord29(),
                getQtyord30(),
                getQtyord31(),
                getQtyord32(),
                getQtyord33(),
                getQtyord34(),
                getQtyord35(),
                getQtyord36(),
                getQtyord37(),
                getQtyord38(),
                getQtyord39(),
                getQtyord40(),
                getQtyord41(),
                getQtyord42(),
                getQtyord43(),
                getQtyord44(),
                getQtyord45(),
                getQtyord46(),
                getQtyord47(),
                getQtyord48(),
                getTotpcs(),
                getAvgcutavg(),
                getAvgcutavgFabclr(),
                getBal1(),
                getBal2(),
                getBal3(),
                getBal4(),
                getBal5(),
                getBal6(),
                getBal7(),
                getBal8(),
                getBal9(),
                getBal10(),
                getBal11(),
                getBal12(),
                getBal13(),
                getBal14(),
                getBal15(),
                getBal16(),
                getBal17(),
                getBal18(),
                getBal19(),
                getBal20(),
                getBal21(),
                getBal22(),
                getBal23(),
                getBal24(),
                getBal25(),
                getBal26(),
                getBal27(),
                getBal28(),
                getBal29(),
                getBal30(),
                getBal31(),
                getBal32(),
                getBal33(),
                getBal34(),
                getBal35(),
                getBal36(),
                getBal37(),
                getBal38(),
                getBal39(),
                getBal40(),
                getBal41(),
                getBal42(),
                getBal43(),
                getBal44(),
                getBal45(),
                getBal46(),
                getBal47(),
                getBal48(),
                getTotbal(),
                getComp1(),
                getComp2(),
                getComp3(),
                getComp4(),
                getComp5(),
                getComp6(),
                getComp7(),
                getComp8(),
                getComp9(),
                getComp10(),
                getComp11(),
                getComp12(),
                getComp13(),
                getComp14(),
                getComp15(),
                getComp16(),
                getComp17(),
                getComp18(),
                getComp19(),
                getComp20(),
                getComp21(),
                getComp22(),
                getComp23(),
                getComp24(),
                getComp25(),
                getComp26(),
                getComp27(),
                getComp28(),
                getComp29(),
                getComp30(),
                getComp31(),
                getComp32(),
                getComp33(),
                getComp34(),
                getComp35(),
                getComp36(),
                getComp37(),
                getComp38(),
                getComp39(),
                getComp40(),
                getComp41(),
                getComp42(),
                getComp43(),
                getComp44(),
                getComp45(),
                getComp46(),
                getComp47(),
                getComp48(),
                getTotcomp());
    }
}