/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0GetCu900dyejobResponsePoutDyejobs implements Serializable {


    @ColumnAlias("CUTSEQ")
    private Short cutseq;

    @ColumnAlias("CUTLCN")
    private String cutlcn;

    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("CLRSEQG")
    private Byte clrseqg;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("W_FABTYP")
    private String wfabtyp;

    @ColumnAlias("W_DYESTS")
    private String wdyests;

    @ColumnAlias("FABSTS")
    private String fabsts;

    @ColumnAlias("W_FINALISEDWID")
    private BigInteger wfinalisedwid;

    @ColumnAlias("RELAXEDWID")
    private Float relaxedwid;

    @ColumnAlias("GEOMETRYNAME")
    private String geometryname;

    @ColumnAlias("RELAXEDLEN")
    private Double relaxedlen;

    @ColumnAlias("PATTFILENAME")
    private String pattfilename;

    @ColumnAlias("MANUAL_MARKERIND")
    private String manualMarkerind;

    @ColumnAlias("ORIGINAL_MARKERFILENAME")
    private String originalMarkerfilename;

    @ColumnAlias("GMTCMPLXITY")
    private String gmtcmplxity;

    @ColumnAlias("NUMPLY")
    private Short numply;

    @ColumnAlias("JOBEXEFILENAME")
    private String jobexefilename;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("MARKERFILENAME")
    private String markerfilename;

    @ColumnAlias("INSTRUCTIONFILENAME")
    private String instructionfilename;

    @ColumnAlias("CUTTER_SENDDAT")
    private LocalDateTime cutterSenddat;

    @ColumnAlias("CREATEID")
    private String createid;

    @ColumnAlias("CREATEDATE")
    private LocalDateTime createdate;

    @ColumnAlias("RELID")
    private String relid;

    @ColumnAlias("RELDATE")
    private LocalDateTime reldate;

    @ColumnAlias("W_FABCPS")
    private String wfabcps;

    @ColumnAlias("W_SKUNO")
    private String wskuno;

    @ColumnAlias("W_GMTDES")
    private String wgmtdes;

    @ColumnAlias("W_GCLRDES")
    private String wgclrdes;

    @ColumnAlias("RDYEJOB")
    private String rdyejob;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("CUTJOBNAME")
    private String cutjobname;

    @ColumnAlias("CANCELID")
    private String cancelid;

    @ColumnAlias("CANCELDATE")
    private LocalDateTime canceldate;

    @ColumnAlias("W_CALSTN")
    private String wcalstn;

    @ColumnAlias("W_FABIND")
    private String wfabind;

    @ColumnAlias("W_FABWGT")
    private BigInteger wfabwgt;

    @ColumnAlias("W_MCHGAU")
    private BigInteger wmchgau;

    @ColumnAlias("W_FABORIEN")
    private BigInteger wfaborien;

    @ColumnAlias("WFABORIENDES")
    private String wfaboriendes;

    @ColumnAlias("W_MRKRTYPDES")
    private String wmrkrtypdes;

    @ColumnAlias("W_MRKRTYP")
    private String wmrkrtyp;

    public Short getCutseq() {
        return this.cutseq;
    }

    public void setCutseq(Short cutseq) {
        this.cutseq = cutseq;
    }

    public String getCutlcn() {
        return this.cutlcn;
    }

    public void setCutlcn(String cutlcn) {
        this.cutlcn = cutlcn;
    }

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseqg() {
        return this.clrseqg;
    }

    public void setClrseqg(Byte clrseqg) {
        this.clrseqg = clrseqg;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getWfabtyp() {
        return this.wfabtyp;
    }

    public void setWfabtyp(String wfabtyp) {
        this.wfabtyp = wfabtyp;
    }

    public String getWdyests() {
        return this.wdyests;
    }

    public void setWdyests(String wdyests) {
        this.wdyests = wdyests;
    }

    public String getFabsts() {
        return this.fabsts;
    }

    public void setFabsts(String fabsts) {
        this.fabsts = fabsts;
    }

    public BigInteger getWfinalisedwid() {
        return this.wfinalisedwid;
    }

    public void setWfinalisedwid(BigInteger wfinalisedwid) {
        this.wfinalisedwid = wfinalisedwid;
    }

    public Float getRelaxedwid() {
        return this.relaxedwid;
    }

    public void setRelaxedwid(Float relaxedwid) {
        this.relaxedwid = relaxedwid;
    }

    public String getGeometryname() {
        return this.geometryname;
    }

    public void setGeometryname(String geometryname) {
        this.geometryname = geometryname;
    }

    public Double getRelaxedlen() {
        return this.relaxedlen;
    }

    public void setRelaxedlen(Double relaxedlen) {
        this.relaxedlen = relaxedlen;
    }

    public String getPattfilename() {
        return this.pattfilename;
    }

    public void setPattfilename(String pattfilename) {
        this.pattfilename = pattfilename;
    }

    public String getManualMarkerind() {
        return this.manualMarkerind;
    }

    public void setManualMarkerind(String manualMarkerind) {
        this.manualMarkerind = manualMarkerind;
    }

    public String getOriginalMarkerfilename() {
        return this.originalMarkerfilename;
    }

    public void setOriginalMarkerfilename(String originalMarkerfilename) {
        this.originalMarkerfilename = originalMarkerfilename;
    }

    public String getGmtcmplxity() {
        return this.gmtcmplxity;
    }

    public void setGmtcmplxity(String gmtcmplxity) {
        this.gmtcmplxity = gmtcmplxity;
    }

    public Short getNumply() {
        return this.numply;
    }

    public void setNumply(Short numply) {
        this.numply = numply;
    }

    public String getJobexefilename() {
        return this.jobexefilename;
    }

    public void setJobexefilename(String jobexefilename) {
        this.jobexefilename = jobexefilename;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMarkerfilename() {
        return this.markerfilename;
    }

    public void setMarkerfilename(String markerfilename) {
        this.markerfilename = markerfilename;
    }

    public String getInstructionfilename() {
        return this.instructionfilename;
    }

    public void setInstructionfilename(String instructionfilename) {
        this.instructionfilename = instructionfilename;
    }

    public LocalDateTime getCutterSenddat() {
        return this.cutterSenddat;
    }

    public void setCutterSenddat(LocalDateTime cutterSenddat) {
        this.cutterSenddat = cutterSenddat;
    }

    public String getCreateid() {
        return this.createid;
    }

    public void setCreateid(String createid) {
        this.createid = createid;
    }

    public LocalDateTime getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(LocalDateTime createdate) {
        this.createdate = createdate;
    }

    public String getRelid() {
        return this.relid;
    }

    public void setRelid(String relid) {
        this.relid = relid;
    }

    public LocalDateTime getReldate() {
        return this.reldate;
    }

    public void setReldate(LocalDateTime reldate) {
        this.reldate = reldate;
    }

    public String getWfabcps() {
        return this.wfabcps;
    }

    public void setWfabcps(String wfabcps) {
        this.wfabcps = wfabcps;
    }

    public String getWskuno() {
        return this.wskuno;
    }

    public void setWskuno(String wskuno) {
        this.wskuno = wskuno;
    }

    public String getWgmtdes() {
        return this.wgmtdes;
    }

    public void setWgmtdes(String wgmtdes) {
        this.wgmtdes = wgmtdes;
    }

    public String getWgclrdes() {
        return this.wgclrdes;
    }

    public void setWgclrdes(String wgclrdes) {
        this.wgclrdes = wgclrdes;
    }

    public String getRdyejob() {
        return this.rdyejob;
    }

    public void setRdyejob(String rdyejob) {
        this.rdyejob = rdyejob;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getCutjobname() {
        return this.cutjobname;
    }

    public void setCutjobname(String cutjobname) {
        this.cutjobname = cutjobname;
    }

    public String getCancelid() {
        return this.cancelid;
    }

    public void setCancelid(String cancelid) {
        this.cancelid = cancelid;
    }

    public LocalDateTime getCanceldate() {
        return this.canceldate;
    }

    public void setCanceldate(LocalDateTime canceldate) {
        this.canceldate = canceldate;
    }

    public String getWcalstn() {
        return this.wcalstn;
    }

    public void setWcalstn(String wcalstn) {
        this.wcalstn = wcalstn;
    }

    public String getWfabind() {
        return this.wfabind;
    }

    public void setWfabind(String wfabind) {
        this.wfabind = wfabind;
    }

    public BigInteger getWfabwgt() {
        return this.wfabwgt;
    }

    public void setWfabwgt(BigInteger wfabwgt) {
        this.wfabwgt = wfabwgt;
    }

    public BigInteger getWmchgau() {
        return this.wmchgau;
    }

    public void setWmchgau(BigInteger wmchgau) {
        this.wmchgau = wmchgau;
    }

    public BigInteger getWfaborien() {
        return this.wfaborien;
    }

    public void setWfaborien(BigInteger wfaborien) {
        this.wfaborien = wfaborien;
    }

    public String getWfaboriendes() {
        return this.wfaboriendes;
    }

    public void setWfaboriendes(String wfaboriendes) {
        this.wfaboriendes = wfaboriendes;
    }

    public String getWmrkrtypdes() {
        return this.wmrkrtypdes;
    }

    public void setWmrkrtypdes(String wmrkrtypdes) {
        this.wmrkrtypdes = wmrkrtypdes;
    }

    public String getWmrkrtyp() {
        return this.wmrkrtyp;
    }

    public void setWmrkrtyp(String wmrkrtyp) {
        this.wmrkrtyp = wmrkrtyp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0GetCu900dyejobResponsePoutDyejobs)) return false;
        final ProcCu1000pk0GetCu900dyejobResponsePoutDyejobs procCu1000pk0getCu900dyejobResponsePoutDyejobs = (ProcCu1000pk0GetCu900dyejobResponsePoutDyejobs) o;
        return Objects.equals(getCutseq(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCutseq()) &&
                Objects.equals(getCutlcn(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCutlcn()) &&
                Objects.equals(getDyejob(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getDyejob()) &&
                Objects.equals(getOrdnum(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getOrdnum()) &&
                Objects.equals(getGmtseq(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getGmtseq()) &&
                Objects.equals(getClrseqg(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getClrseqg()) &&
                Objects.equals(getFabseq(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getFabseq()) &&
                Objects.equals(getWfabtyp(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfabtyp()) &&
                Objects.equals(getWdyests(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWdyests()) &&
                Objects.equals(getFabsts(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getFabsts()) &&
                Objects.equals(getWfinalisedwid(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfinalisedwid()) &&
                Objects.equals(getRelaxedwid(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getRelaxedwid()) &&
                Objects.equals(getGeometryname(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getGeometryname()) &&
                Objects.equals(getRelaxedlen(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getRelaxedlen()) &&
                Objects.equals(getPattfilename(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getPattfilename()) &&
                Objects.equals(getManualMarkerind(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getManualMarkerind()) &&
                Objects.equals(getOriginalMarkerfilename(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getOriginalMarkerfilename()) &&
                Objects.equals(getGmtcmplxity(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getGmtcmplxity()) &&
                Objects.equals(getNumply(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getNumply()) &&
                Objects.equals(getJobexefilename(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getJobexefilename()) &&
                Objects.equals(getStatus(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getStatus()) &&
                Objects.equals(getMarkerfilename(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getMarkerfilename()) &&
                Objects.equals(getInstructionfilename(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getInstructionfilename()) &&
                Objects.equals(getCutterSenddat(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCutterSenddat()) &&
                Objects.equals(getCreateid(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCreateid()) &&
                Objects.equals(getCreatedate(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCreatedate()) &&
                Objects.equals(getRelid(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getRelid()) &&
                Objects.equals(getReldate(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getReldate()) &&
                Objects.equals(getWfabcps(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfabcps()) &&
                Objects.equals(getWskuno(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWskuno()) &&
                Objects.equals(getWgmtdes(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWgmtdes()) &&
                Objects.equals(getWgclrdes(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWgclrdes()) &&
                Objects.equals(getRdyejob(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getRdyejob()) &&
                Objects.equals(getRemarks(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getRemarks()) &&
                Objects.equals(getCutjobname(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCutjobname()) &&
                Objects.equals(getCancelid(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCancelid()) &&
                Objects.equals(getCanceldate(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getCanceldate()) &&
                Objects.equals(getWcalstn(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWcalstn()) &&
                Objects.equals(getWfabind(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfabind()) &&
                Objects.equals(getWfabwgt(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfabwgt()) &&
                Objects.equals(getWmchgau(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWmchgau()) &&
                Objects.equals(getWfaborien(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfaborien()) &&
                Objects.equals(getWfaboriendes(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWfaboriendes()) &&
                Objects.equals(getWmrkrtypdes(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWmrkrtypdes()) &&
                Objects.equals(getWmrkrtyp(), procCu1000pk0getCu900dyejobResponsePoutDyejobs.getWmrkrtyp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCutseq(),
                getCutlcn(),
                getDyejob(),
                getOrdnum(),
                getGmtseq(),
                getClrseqg(),
                getFabseq(),
                getWfabtyp(),
                getWdyests(),
                getFabsts(),
                getWfinalisedwid(),
                getRelaxedwid(),
                getGeometryname(),
                getRelaxedlen(),
                getPattfilename(),
                getManualMarkerind(),
                getOriginalMarkerfilename(),
                getGmtcmplxity(),
                getNumply(),
                getJobexefilename(),
                getStatus(),
                getMarkerfilename(),
                getInstructionfilename(),
                getCutterSenddat(),
                getCreateid(),
                getCreatedate(),
                getRelid(),
                getReldate(),
                getWfabcps(),
                getWskuno(),
                getWgmtdes(),
                getWgclrdes(),
                getRdyejob(),
                getRemarks(),
                getCutjobname(),
                getCancelid(),
                getCanceldate(),
                getWcalstn(),
                getWfabind(),
                getWfabwgt(),
                getWmchgau(),
                getWfaborien(),
                getWfaboriendes(),
                getWmrkrtypdes(),
                getWmrkrtyp());
    }
}