/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryJobCutOrderResponsePoutOrderDetail implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("MAKLCN")
    private String maklcn;

    @ColumnAlias("SSHPDAT")
    private String sshpdat;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("QTYORD")
    private Integer qtyord;

    @ColumnAlias("PCKUNT")
    private Byte pckunt;

    @ColumnAlias("MERCHANDISER")
    private String merchandiser;

    @ColumnAlias("DYEJOB")
    private String dyejob;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    public String getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(String sshpdat) {
        this.sshpdat = sshpdat;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    public Byte getPckunt() {
        return this.pckunt;
    }

    public void setPckunt(Byte pckunt) {
        this.pckunt = pckunt;
    }

    public String getMerchandiser() {
        return this.merchandiser;
    }

    public void setMerchandiser(String merchandiser) {
        this.merchandiser = merchandiser;
    }

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryJobCutOrderResponsePoutOrderDetail)) return false;
        final ProcCu1000pk0QryJobCutOrderResponsePoutOrderDetail procCu1000pk0qryJobCutOrderResponsePoutOrderDetail = (ProcCu1000pk0QryJobCutOrderResponsePoutOrderDetail) o;
        return Objects.equals(getOrdnum(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getOrdnum()) &&
                Objects.equals(getMaklcn(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getMaklcn()) &&
                Objects.equals(getSshpdat(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getSshpdat()) &&
                Objects.equals(getClicod(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getClicod()) &&
                Objects.equals(getQtyord(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getQtyord()) &&
                Objects.equals(getPckunt(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getPckunt()) &&
                Objects.equals(getMerchandiser(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getMerchandiser()) &&
                Objects.equals(getDyejob(), procCu1000pk0qryJobCutOrderResponsePoutOrderDetail.getDyejob());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getMaklcn(),
                getSshpdat(),
                getClicod(),
                getQtyord(),
                getPckunt(),
                getMerchandiser(),
                getDyejob());
    }
}