/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryCutBySizeOrderDetResponse implements Serializable {


    @ColumnAlias("pOutOrderDet")
    private List<ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet> poutOrderDet;

    @ColumnAlias("pOutSizes")
    private List<ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes> poutSizes;

    public List<ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet> getPoutOrderDet() {
        return this.poutOrderDet;
    }

    public void setPoutOrderDet(List<ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet> poutOrderDet) {
        this.poutOrderDet = poutOrderDet;
    }

    public List<ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes> getPoutSizes() {
        return this.poutSizes;
    }

    public void setPoutSizes(List<ProcCu1000pk0QryCutBySizeOrderDetResponsePoutSizes> poutSizes) {
        this.poutSizes = poutSizes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryCutBySizeOrderDetResponse)) return false;
        final ProcCu1000pk0QryCutBySizeOrderDetResponse procCu1000pk0qryCutBySizeOrderDetResponse = (ProcCu1000pk0QryCutBySizeOrderDetResponse) o;
        return Objects.equals(getPoutOrderDet(), procCu1000pk0qryCutBySizeOrderDetResponse.getPoutOrderDet()) &&
                Objects.equals(getPoutSizes(), procCu1000pk0qryCutBySizeOrderDetResponse.getPoutSizes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutOrderDet(),
                getPoutSizes());
    }
}