/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QueryJobscutResponsePoutJobscutList implements Serializable {


    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("CLRDES")
    private String clrdes;

    @ColumnAlias("TRFFLG")
    private String trfflg;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("FABWGT")
    private Short fabwgt;

    @ColumnAlias("DYEUNT")
    private String dyeunt;

    @ColumnAlias("DYESTS")
    private String dyests;

    @ColumnAlias("DYEDESC")
    private String dyedesc;

    @ColumnAlias("AMTREQ")
    private Double amtreq;

    @ColumnAlias("WGTCMP")
    private Double wgtcmp;

    @ColumnAlias("WGTDEL")
    private Double wgtdel;

    @ColumnAlias("KGS")
    private Double kgs;

    @ColumnAlias("KGSCUT")
    private Double kgscut;

    @ColumnAlias("CUTLCN")
    private String cutlcn;

    @ColumnAlias("CUTSTS")
    private String cutsts;

    @ColumnAlias("CUTDATE")
    private LocalDateTime cutdate;

    @ColumnAlias("PCSCUT")
    private Integer pcscut;

    @ColumnAlias("LOADATE")
    private LocalDateTime loadate;

    @ColumnAlias("PCSLOAD")
    private Double pcsload;

    @ColumnAlias("W_DELNUM")
    private String wdelnum;

    @ColumnAlias("W_DATDEL")
    private LocalDateTime wdatdel;

    @ColumnAlias("TOTREQ")
    private Double totreq;

    @ColumnAlias("TOTDYE")
    private Double totdye;

    @ColumnAlias("TOTDEL")
    private Double totdel;

    @ColumnAlias("KGSRCV")
    private Integer kgsrcv;

    @ColumnAlias("SUMKGSCUT")
    private Double sumkgscut;

    @ColumnAlias("TOTCUT")
    private Double totcut;

    @ColumnAlias("TOTLOAD")
    private BigInteger totload;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("DELDAT")
    private LocalDateTime deldat;

    @ColumnAlias("DDELNUM")
    private String ddelnum;

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getClrdes() {
        return this.clrdes;
    }

    public void setClrdes(String clrdes) {
        this.clrdes = clrdes;
    }

    public String getTrfflg() {
        return this.trfflg;
    }

    public void setTrfflg(String trfflg) {
        this.trfflg = trfflg;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public Short getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(Short fabwgt) {
        this.fabwgt = fabwgt;
    }

    public String getDyeunt() {
        return this.dyeunt;
    }

    public void setDyeunt(String dyeunt) {
        this.dyeunt = dyeunt;
    }

    public String getDyests() {
        return this.dyests;
    }

    public void setDyests(String dyests) {
        this.dyests = dyests;
    }

    public String getDyedesc() {
        return this.dyedesc;
    }

    public void setDyedesc(String dyedesc) {
        this.dyedesc = dyedesc;
    }

    public Double getAmtreq() {
        return this.amtreq;
    }

    public void setAmtreq(Double amtreq) {
        this.amtreq = amtreq;
    }

    public Double getWgtcmp() {
        return this.wgtcmp;
    }

    public void setWgtcmp(Double wgtcmp) {
        this.wgtcmp = wgtcmp;
    }

    public Double getWgtdel() {
        return this.wgtdel;
    }

    public void setWgtdel(Double wgtdel) {
        this.wgtdel = wgtdel;
    }

    public Double getKgs() {
        return this.kgs;
    }

    public void setKgs(Double kgs) {
        this.kgs = kgs;
    }

    public Double getKgscut() {
        return this.kgscut;
    }

    public void setKgscut(Double kgscut) {
        this.kgscut = kgscut;
    }

    public String getCutlcn() {
        return this.cutlcn;
    }

    public void setCutlcn(String cutlcn) {
        this.cutlcn = cutlcn;
    }

    public String getCutsts() {
        return this.cutsts;
    }

    public void setCutsts(String cutsts) {
        this.cutsts = cutsts;
    }

    public LocalDateTime getCutdate() {
        return this.cutdate;
    }

    public void setCutdate(LocalDateTime cutdate) {
        this.cutdate = cutdate;
    }

    public Integer getPcscut() {
        return this.pcscut;
    }

    public void setPcscut(Integer pcscut) {
        this.pcscut = pcscut;
    }

    public LocalDateTime getLoadate() {
        return this.loadate;
    }

    public void setLoadate(LocalDateTime loadate) {
        this.loadate = loadate;
    }

    public Double getPcsload() {
        return this.pcsload;
    }

    public void setPcsload(Double pcsload) {
        this.pcsload = pcsload;
    }

    public String getWdelnum() {
        return this.wdelnum;
    }

    public void setWdelnum(String wdelnum) {
        this.wdelnum = wdelnum;
    }

    public LocalDateTime getWdatdel() {
        return this.wdatdel;
    }

    public void setWdatdel(LocalDateTime wdatdel) {
        this.wdatdel = wdatdel;
    }

    public Double getTotreq() {
        return this.totreq;
    }

    public void setTotreq(Double totreq) {
        this.totreq = totreq;
    }

    public Double getTotdye() {
        return this.totdye;
    }

    public void setTotdye(Double totdye) {
        this.totdye = totdye;
    }

    public Double getTotdel() {
        return this.totdel;
    }

    public void setTotdel(Double totdel) {
        this.totdel = totdel;
    }

    public Integer getKgsrcv() {
        return this.kgsrcv;
    }

    public void setKgsrcv(Integer kgsrcv) {
        this.kgsrcv = kgsrcv;
    }

    public Double getSumkgscut() {
        return this.sumkgscut;
    }

    public void setSumkgscut(Double sumkgscut) {
        this.sumkgscut = sumkgscut;
    }

    public Double getTotcut() {
        return this.totcut;
    }

    public void setTotcut(Double totcut) {
        this.totcut = totcut;
    }

    public BigInteger getTotload() {
        return this.totload;
    }

    public void setTotload(BigInteger totload) {
        this.totload = totload;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public LocalDateTime getDeldat() {
        return this.deldat;
    }

    public void setDeldat(LocalDateTime deldat) {
        this.deldat = deldat;
    }

    public String getDdelnum() {
        return this.ddelnum;
    }

    public void setDdelnum(String ddelnum) {
        this.ddelnum = ddelnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QueryJobscutResponsePoutJobscutList)) return false;
        final ProcCu1000pk0QueryJobscutResponsePoutJobscutList procCu1000pk0queryJobscutResponsePoutJobscutList = (ProcCu1000pk0QueryJobscutResponsePoutJobscutList) o;
        return Objects.equals(getDyejob(), procCu1000pk0queryJobscutResponsePoutJobscutList.getDyejob()) &&
                Objects.equals(getClrseq(), procCu1000pk0queryJobscutResponsePoutJobscutList.getClrseq()) &&
                Objects.equals(getClrdes(), procCu1000pk0queryJobscutResponsePoutJobscutList.getClrdes()) &&
                Objects.equals(getTrfflg(), procCu1000pk0queryJobscutResponsePoutJobscutList.getTrfflg()) &&
                Objects.equals(getFabseq(), procCu1000pk0queryJobscutResponsePoutJobscutList.getFabseq()) &&
                Objects.equals(getFabtyp(), procCu1000pk0queryJobscutResponsePoutJobscutList.getFabtyp()) &&
                Objects.equals(getFabwgt(), procCu1000pk0queryJobscutResponsePoutJobscutList.getFabwgt()) &&
                Objects.equals(getDyeunt(), procCu1000pk0queryJobscutResponsePoutJobscutList.getDyeunt()) &&
                Objects.equals(getDyests(), procCu1000pk0queryJobscutResponsePoutJobscutList.getDyests()) &&
                Objects.equals(getDyedesc(), procCu1000pk0queryJobscutResponsePoutJobscutList.getDyedesc()) &&
                Objects.equals(getAmtreq(), procCu1000pk0queryJobscutResponsePoutJobscutList.getAmtreq()) &&
                Objects.equals(getWgtcmp(), procCu1000pk0queryJobscutResponsePoutJobscutList.getWgtcmp()) &&
                Objects.equals(getWgtdel(), procCu1000pk0queryJobscutResponsePoutJobscutList.getWgtdel()) &&
                Objects.equals(getKgs(), procCu1000pk0queryJobscutResponsePoutJobscutList.getKgs()) &&
                Objects.equals(getKgscut(), procCu1000pk0queryJobscutResponsePoutJobscutList.getKgscut()) &&
                Objects.equals(getCutlcn(), procCu1000pk0queryJobscutResponsePoutJobscutList.getCutlcn()) &&
                Objects.equals(getCutsts(), procCu1000pk0queryJobscutResponsePoutJobscutList.getCutsts()) &&
                Objects.equals(getCutdate(), procCu1000pk0queryJobscutResponsePoutJobscutList.getCutdate()) &&
                Objects.equals(getPcscut(), procCu1000pk0queryJobscutResponsePoutJobscutList.getPcscut()) &&
                Objects.equals(getLoadate(), procCu1000pk0queryJobscutResponsePoutJobscutList.getLoadate()) &&
                Objects.equals(getPcsload(), procCu1000pk0queryJobscutResponsePoutJobscutList.getPcsload()) &&
                Objects.equals(getWdelnum(), procCu1000pk0queryJobscutResponsePoutJobscutList.getWdelnum()) &&
                Objects.equals(getWdatdel(), procCu1000pk0queryJobscutResponsePoutJobscutList.getWdatdel()) &&
                Objects.equals(getTotreq(), procCu1000pk0queryJobscutResponsePoutJobscutList.getTotreq()) &&
                Objects.equals(getTotdye(), procCu1000pk0queryJobscutResponsePoutJobscutList.getTotdye()) &&
                Objects.equals(getTotdel(), procCu1000pk0queryJobscutResponsePoutJobscutList.getTotdel()) &&
                Objects.equals(getKgsrcv(), procCu1000pk0queryJobscutResponsePoutJobscutList.getKgsrcv()) &&
                Objects.equals(getSumkgscut(), procCu1000pk0queryJobscutResponsePoutJobscutList.getSumkgscut()) &&
                Objects.equals(getTotcut(), procCu1000pk0queryJobscutResponsePoutJobscutList.getTotcut()) &&
                Objects.equals(getTotload(), procCu1000pk0queryJobscutResponsePoutJobscutList.getTotload()) &&
                Objects.equals(getOrdnum(), procCu1000pk0queryJobscutResponsePoutJobscutList.getOrdnum()) &&
                Objects.equals(getDeldat(), procCu1000pk0queryJobscutResponsePoutJobscutList.getDeldat()) &&
                Objects.equals(getDdelnum(), procCu1000pk0queryJobscutResponsePoutJobscutList.getDdelnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDyejob(),
                getClrseq(),
                getClrdes(),
                getTrfflg(),
                getFabseq(),
                getFabtyp(),
                getFabwgt(),
                getDyeunt(),
                getDyests(),
                getDyedesc(),
                getAmtreq(),
                getWgtcmp(),
                getWgtdel(),
                getKgs(),
                getKgscut(),
                getCutlcn(),
                getCutsts(),
                getCutdate(),
                getPcscut(),
                getLoadate(),
                getPcsload(),
                getWdelnum(),
                getWdatdel(),
                getTotreq(),
                getTotdye(),
                getTotdel(),
                getKgsrcv(),
                getSumkgscut(),
                getTotcut(),
                getTotload(),
                getOrdnum(),
                getDeldat(),
                getDdelnum());
    }
}