/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("W_CLRDES")
    private String wclrdes;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("W_GMTDES")
    private String wgmtdes;

    @ColumnAlias("FABCLR")
    private String fabclr;

    @ColumnAlias("W_CLICOD")
    private String wclicod;

    @ColumnAlias("W_SSHPDAT")
    private LocalDateTime wsshpdat;

    @ColumnAlias("W_MRCID")
    private String wmrcid;

    @ColumnAlias("W_MRCNAME")
    private String wmrcname;

    @ColumnAlias("W_MAKLCN")
    private String wmaklcn;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getWclrdes() {
        return this.wclrdes;
    }

    public void setWclrdes(String wclrdes) {
        this.wclrdes = wclrdes;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public String getWgmtdes() {
        return this.wgmtdes;
    }

    public void setWgmtdes(String wgmtdes) {
        this.wgmtdes = wgmtdes;
    }

    public String getFabclr() {
        return this.fabclr;
    }

    public void setFabclr(String fabclr) {
        this.fabclr = fabclr;
    }

    public String getWclicod() {
        return this.wclicod;
    }

    public void setWclicod(String wclicod) {
        this.wclicod = wclicod;
    }

    public LocalDateTime getWsshpdat() {
        return this.wsshpdat;
    }

    public void setWsshpdat(LocalDateTime wsshpdat) {
        this.wsshpdat = wsshpdat;
    }

    public String getWmrcid() {
        return this.wmrcid;
    }

    public void setWmrcid(String wmrcid) {
        this.wmrcid = wmrcid;
    }

    public String getWmrcname() {
        return this.wmrcname;
    }

    public void setWmrcname(String wmrcname) {
        this.wmrcname = wmrcname;
    }

    public String getWmaklcn() {
        return this.wmaklcn;
    }

    public void setWmaklcn(String wmaklcn) {
        this.wmaklcn = wmaklcn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet)) return false;
        final ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet = (ProcCu1000pk0QryCutBySizeOrderDetResponsePoutOrderDet) o;
        return Objects.equals(getOrdnum(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getOrdnum()) &&
                Objects.equals(getClrseq(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getClrseq()) &&
                Objects.equals(getWclrdes(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWclrdes()) &&
                Objects.equals(getGmtseq(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getGmtseq()) &&
                Objects.equals(getWgmtdes(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWgmtdes()) &&
                Objects.equals(getFabclr(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getFabclr()) &&
                Objects.equals(getWclicod(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWclicod()) &&
                Objects.equals(getWsshpdat(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWsshpdat()) &&
                Objects.equals(getWmrcid(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWmrcid()) &&
                Objects.equals(getWmrcname(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWmrcname()) &&
                Objects.equals(getWmaklcn(), procCu1000pk0qryCutBySizeOrderDetResponsePoutOrderDet.getWmaklcn());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getClrseq(),
                getWclrdes(),
                getGmtseq(),
                getWgmtdes(),
                getFabclr(),
                getWclicod(),
                getWsshpdat(),
                getWmrcid(),
                getWmrcname(),
                getWmaklcn());
    }
}