/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu1000pk0SprocGetLastremarkCutstsResponse implements Serializable {


    @ColumnAlias("pOutCutsts")
    private List<ProcCu1000pk0SprocGetLastremarkCutstsResponsePoutCutsts> poutCutsts;

    public List<ProcCu1000pk0SprocGetLastremarkCutstsResponsePoutCutsts> getPoutCutsts() {
        return this.poutCutsts;
    }

    public void setPoutCutsts(List<ProcCu1000pk0SprocGetLastremarkCutstsResponsePoutCutsts> poutCutsts) {
        this.poutCutsts = poutCutsts;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu1000pk0SprocGetLastremarkCutstsResponse)) return false;
        final ProcCu1000pk0SprocGetLastremarkCutstsResponse procCu1000pk0sprocGetLastremarkCutstsResponse = (ProcCu1000pk0SprocGetLastremarkCutstsResponse) o;
        return Objects.equals(getPoutCutsts(), procCu1000pk0sprocGetLastremarkCutstsResponse.getPoutCutsts());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCutsts());
    }
}