/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCu100pk0GetLastRemDetResponsePoutDetailBlock implements Serializable {


    @ColumnAlias("CUTREM")
    private String cutrem;

    @ColumnAlias("CUTLCN")
    private String cutlcn;

    @ColumnAlias("CUTSTS")
    private String cutsts;

    @ColumnAlias("W_CUTSTSDESC")
    private String wcutstsdesc;

    @ColumnAlias("CUTSTSID")
    private String cutstsid;

    @ColumnAlias("CUTSTSDAT")
    private LocalDateTime cutstsdat;

    @ColumnAlias("CUTUSRDAT")
    private LocalDateTime cutusrdat;

    @ColumnAlias("CUTUSRID")
    private String cutusrid;

    @ColumnAlias("MAKREM")
    private String makrem;

    @ColumnAlias("MAKUSRDAT")
    private LocalDateTime makusrdat;

    @ColumnAlias("MAKUSRID")
    private String makusrid;

    @ColumnAlias("ULDREM")
    private String uldrem;

    @ColumnAlias("ULDUSRDAT")
    private LocalDateTime uldusrdat;

    @ColumnAlias("ULDUSRID")
    private String uldusrid;

    @ColumnAlias("EMBREM")
    private String embrem;

    @ColumnAlias("EMBUSRDAT")
    private LocalDateTime embusrdat;

    @ColumnAlias("EMBUSRID")
    private String embusrid;

    @ColumnAlias("CUTEXC")
    private String cutexc;

    @ColumnAlias("MAKEXC")
    private String makexc;

    @ColumnAlias("EMBEXC")
    private String embexc;

    @ColumnAlias("ULDEXC")
    private String uldexc;

    public String getCutrem() {
        return this.cutrem;
    }

    public void setCutrem(String cutrem) {
        this.cutrem = cutrem;
    }

    public String getCutlcn() {
        return this.cutlcn;
    }

    public void setCutlcn(String cutlcn) {
        this.cutlcn = cutlcn;
    }

    public String getCutsts() {
        return this.cutsts;
    }

    public void setCutsts(String cutsts) {
        this.cutsts = cutsts;
    }

    public String getWcutstsdesc() {
        return this.wcutstsdesc;
    }

    public void setWcutstsdesc(String wcutstsdesc) {
        this.wcutstsdesc = wcutstsdesc;
    }

    public String getCutstsid() {
        return this.cutstsid;
    }

    public void setCutstsid(String cutstsid) {
        this.cutstsid = cutstsid;
    }

    public LocalDateTime getCutstsdat() {
        return this.cutstsdat;
    }

    public void setCutstsdat(LocalDateTime cutstsdat) {
        this.cutstsdat = cutstsdat;
    }

    public LocalDateTime getCutusrdat() {
        return this.cutusrdat;
    }

    public void setCutusrdat(LocalDateTime cutusrdat) {
        this.cutusrdat = cutusrdat;
    }

    public String getCutusrid() {
        return this.cutusrid;
    }

    public void setCutusrid(String cutusrid) {
        this.cutusrid = cutusrid;
    }

    public String getMakrem() {
        return this.makrem;
    }

    public void setMakrem(String makrem) {
        this.makrem = makrem;
    }

    public LocalDateTime getMakusrdat() {
        return this.makusrdat;
    }

    public void setMakusrdat(LocalDateTime makusrdat) {
        this.makusrdat = makusrdat;
    }

    public String getMakusrid() {
        return this.makusrid;
    }

    public void setMakusrid(String makusrid) {
        this.makusrid = makusrid;
    }

    public String getUldrem() {
        return this.uldrem;
    }

    public void setUldrem(String uldrem) {
        this.uldrem = uldrem;
    }

    public LocalDateTime getUldusrdat() {
        return this.uldusrdat;
    }

    public void setUldusrdat(LocalDateTime uldusrdat) {
        this.uldusrdat = uldusrdat;
    }

    public String getUldusrid() {
        return this.uldusrid;
    }

    public void setUldusrid(String uldusrid) {
        this.uldusrid = uldusrid;
    }

    public String getEmbrem() {
        return this.embrem;
    }

    public void setEmbrem(String embrem) {
        this.embrem = embrem;
    }

    public LocalDateTime getEmbusrdat() {
        return this.embusrdat;
    }

    public void setEmbusrdat(LocalDateTime embusrdat) {
        this.embusrdat = embusrdat;
    }

    public String getEmbusrid() {
        return this.embusrid;
    }

    public void setEmbusrid(String embusrid) {
        this.embusrid = embusrid;
    }

    public String getCutexc() {
        return this.cutexc;
    }

    public void setCutexc(String cutexc) {
        this.cutexc = cutexc;
    }

    public String getMakexc() {
        return this.makexc;
    }

    public void setMakexc(String makexc) {
        this.makexc = makexc;
    }

    public String getEmbexc() {
        return this.embexc;
    }

    public void setEmbexc(String embexc) {
        this.embexc = embexc;
    }

    public String getUldexc() {
        return this.uldexc;
    }

    public void setUldexc(String uldexc) {
        this.uldexc = uldexc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCu100pk0GetLastRemDetResponsePoutDetailBlock)) return false;
        final ProcCu100pk0GetLastRemDetResponsePoutDetailBlock procCu100pk0getLastRemDetResponsePoutDetailBlock = (ProcCu100pk0GetLastRemDetResponsePoutDetailBlock) o;
        return Objects.equals(getCutrem(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutrem()) &&
                Objects.equals(getCutlcn(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutlcn()) &&
                Objects.equals(getCutsts(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutsts()) &&
                Objects.equals(getWcutstsdesc(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getWcutstsdesc()) &&
                Objects.equals(getCutstsid(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutstsid()) &&
                Objects.equals(getCutstsdat(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutstsdat()) &&
                Objects.equals(getCutusrdat(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutusrdat()) &&
                Objects.equals(getCutusrid(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutusrid()) &&
                Objects.equals(getMakrem(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getMakrem()) &&
                Objects.equals(getMakusrdat(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getMakusrdat()) &&
                Objects.equals(getMakusrid(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getMakusrid()) &&
                Objects.equals(getUldrem(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getUldrem()) &&
                Objects.equals(getUldusrdat(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getUldusrdat()) &&
                Objects.equals(getUldusrid(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getUldusrid()) &&
                Objects.equals(getEmbrem(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getEmbrem()) &&
                Objects.equals(getEmbusrdat(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getEmbusrdat()) &&
                Objects.equals(getEmbusrid(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getEmbusrid()) &&
                Objects.equals(getCutexc(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getCutexc()) &&
                Objects.equals(getMakexc(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getMakexc()) &&
                Objects.equals(getEmbexc(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getEmbexc()) &&
                Objects.equals(getUldexc(), procCu100pk0getLastRemDetResponsePoutDetailBlock.getUldexc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCutrem(),
                getCutlcn(),
                getCutsts(),
                getWcutstsdesc(),
                getCutstsid(),
                getCutstsdat(),
                getCutusrdat(),
                getCutusrid(),
                getMakrem(),
                getMakusrdat(),
                getMakusrid(),
                getUldrem(),
                getUldusrdat(),
                getUldusrid(),
                getEmbrem(),
                getEmbusrdat(),
                getEmbusrid(),
                getCutexc(),
                getMakexc(),
                getEmbexc(),
                getUldexc());
    }
}