/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Cut905Id implements Serializable {

    private Short cutseq;
    private Byte sizeseq;
    private String ordnum;
    private String dyejob;
    private String gmtseq;
    private Byte clrseqg;
    private Byte fabseq;

    public Short getCutseq() {
        return this.cutseq;
    }

    public void setCutseq(Short cutseq) {
        this.cutseq = cutseq;
    }

    public Byte getSizeseq() {
        return this.sizeseq;
    }

    public void setSizeseq(Byte sizeseq) {
        this.sizeseq = sizeseq;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseqg() {
        return this.clrseqg;
    }

    public void setClrseqg(Byte clrseqg) {
        this.clrseqg = clrseqg;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Cut905)) return false;
        final Cut905 cut905 = (Cut905) o;
        return Objects.equals(getCutseq(), cut905.getCutseq()) &&
                Objects.equals(getSizeseq(), cut905.getSizeseq()) &&
                Objects.equals(getOrdnum(), cut905.getOrdnum()) &&
                Objects.equals(getDyejob(), cut905.getDyejob()) &&
                Objects.equals(getGmtseq(), cut905.getGmtseq()) &&
                Objects.equals(getClrseqg(), cut905.getClrseqg()) &&
                Objects.equals(getFabseq(), cut905.getFabseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCutseq(),
                getSizeseq(),
                getOrdnum(),
                getDyejob(),
                getGmtseq(),
                getClrseqg(),
                getFabseq());
    }
}