/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Cut905 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`CUT905`")
@IdClass(Cut905Id.class)
public class Cut905 implements Serializable {

    private Short cutseq;
    private Byte sizeseq;
    private String ordnum;
    private String dyejob;
    private String gmtseq;
    private Byte clrseqg;
    private Byte fabseq;
    private String szedes;
    private String lectcod;
    private Float szeratio;
    private String reversedir;
    private Byte groupnum;

    @Id
    @Column(name = "`CUTSEQ`", nullable = false, scale = 0, precision = 3)
    public Short getCutseq() {
        return this.cutseq;
    }

    public void setCutseq(Short cutseq) {
        this.cutseq = cutseq;
    }

    @Id
    @Column(name = "`SIZESEQ`", nullable = false, scale = 0, precision = 2)
    public Byte getSizeseq() {
        return this.sizeseq;
    }

    public void setSizeseq(Byte sizeseq) {
        this.sizeseq = sizeseq;
    }

    @Id
    @Column(name = "`ORDNUM`", nullable = false, length = 12)
    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    @Id
    @Column(name = "`DYEJOB`", nullable = false, length = 9)
    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    @Id
    @Column(name = "`GMTSEQ`", nullable = false, length = 2)
    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    @Id
    @Column(name = "`CLRSEQG`", nullable = false, scale = 0, precision = 2)
    public Byte getClrseqg() {
        return this.clrseqg;
    }

    public void setClrseqg(Byte clrseqg) {
        this.clrseqg = clrseqg;
    }

    @Id
    @Column(name = "`FABSEQ`", nullable = false, scale = 0, precision = 2)
    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    @Column(name = "`SZEDES`", nullable = true, length = 10)
    public String getSzedes() {
        return this.szedes;
    }

    public void setSzedes(String szedes) {
        this.szedes = szedes;
    }

    @Column(name = "`LECTCOD`", nullable = true, length = 4)
    public String getLectcod() {
        return this.lectcod;
    }

    public void setLectcod(String lectcod) {
        this.lectcod = lectcod;
    }

    @Column(name = "`SZERATIO`", nullable = true, scale = 2, precision = 5)
    public Float getSzeratio() {
        return this.szeratio;
    }

    public void setSzeratio(Float szeratio) {
        this.szeratio = szeratio;
    }

    @Column(name = "`REVERSEDIR`", nullable = true, length = 1)
    public String getReversedir() {
        return this.reversedir;
    }

    public void setReversedir(String reversedir) {
        this.reversedir = reversedir;
    }

    @Column(name = "`GROUPNUM`", nullable = true, scale = 0, precision = 2)
    public Byte getGroupnum() {
        return this.groupnum;
    }

    public void setGroupnum(Byte groupnum) {
        this.groupnum = groupnum;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Cut905)) return false;
        final Cut905 cut905 = (Cut905) o;
        return Objects.equals(getCutseq(), cut905.getCutseq()) &&
                Objects.equals(getSizeseq(), cut905.getSizeseq()) &&
                Objects.equals(getOrdnum(), cut905.getOrdnum()) &&
                Objects.equals(getDyejob(), cut905.getDyejob()) &&
                Objects.equals(getGmtseq(), cut905.getGmtseq()) &&
                Objects.equals(getClrseqg(), cut905.getClrseqg()) &&
                Objects.equals(getFabseq(), cut905.getFabseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCutseq(),
                getSizeseq(),
                getOrdnum(),
                getDyejob(),
                getGmtseq(),
                getClrseqg(),
                getFabseq());
    }
}