/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryCu220TrftypResponse implements Serializable {


    @ColumnAlias("TRFTYP1")
    private BigDecimal trftyp1;

    public BigDecimal getTrftyp1() {
        return this.trftyp1;
    }

    public void setTrftyp1(BigDecimal trftyp1) {
        this.trftyp1 = trftyp1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryCu220TrftypResponse)) return false;
        final QryCu220TrftypResponse qryCu220trftypResponse = (QryCu220TrftypResponse) o;
        return Objects.equals(getTrftyp1(), qryCu220trftypResponse.getTrftyp1());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrftyp1());
    }
}