/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.mu.cmt.pfs.pfsdb.models.query.*;

public interface PfsdbQueryExecutorService {

    QryReturnCallPageResponse executeQryReturnCallPage(String pwmprogid, String pparamList);

    QryLectraSzeResponse executeQryLectraSze(String pdyejob, String pgmtseq, String pclrseqg, String pfabseq, String pcutseq, String pordnum);

    Page<QryCutlcnResponse> executeQryCutlcn(Pageable pageable);

    void exportQryCutlcn(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryGetCutfabResponse executeQryGetCUTFAB(String pordnum, Integer pclrseqg, String pgmtseq);

    QryCu220TrftypResponse executeQryCU220_Trftyp(String psdyejob, String pddyejob, Integer psfabseq);

    QrySzeDesResponse executeQrySzeDes(String pdyejob, String pgmtseq, Integer pclrseqg, Integer pfabseq, Integer pcutseq);

    QryUserLocationResponse executeQryUserLocation(String pusrid);

    Page<QryGetItemcodResponse> executeQryGetItemcod(Pageable pageable);

    void exportQryGetItemcod(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}